import type { RawProduct } from '../products';

export const SEG_LUX_A: RawProduct[] = [
  // ─── Bvlgari ───────────────────────────────────────────────
  {
    slug: 'bvlgari-man-in-black', brand: 'Bvlgari', name: 'Man in Black',
    price: 13900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Ром', 'Специи'], heart: ['Ирис', 'Кожа', 'Тубероза'], base: ['Бензоин', 'Бобы тонка', 'Гваяк'] },
    longevityHours: 9, sillage: 4, accords: ['пряный', 'кожаный', 'амбра'],
    desc: 'Ром и кожа в чёрном смокинге — вечерняя классика Bvlgari.',
    accent: '#3A2E28',
  },
  {
    slug: 'bvlgari-aqva-pour-homme', brand: 'Bvlgari', name: 'Aqva Pour Homme',
    price: 10900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: ['хит'],
    notes: { top: ['Мандарин', 'Петигрен'], heart: ['Водоросли', 'Лаванда'], base: ['Кедр', 'Амбра', 'Пачули'] },
    longevityHours: 7, sillage: 3, accords: ['акватический', 'свежий', 'древесный'],
    desc: 'Морская классика Жака Кавалье: цитрус и водоросли — запах чистой средиземноморской воды.',
    accent: '#1B6A8C',
  },
  {
    slug: 'bvlgari-man-wood-essence', brand: 'Bvlgari', name: 'Man Wood Essence',
    price: 12400, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Цитрусы', 'Кориандр'], heart: ['Кипарис', 'Ветивер'], base: ['Кедр', 'Бензоин'] },
    longevityHours: 8, sillage: 3, accords: ['древесный', 'свежий'],
    desc: 'Тёплое благородное дерево с цитрусом — безотказный аромат на работу и каждый день.',
    accent: '#7A5C3E',
  },
  {
    slug: 'bvlgari-man-glacial-essence', brand: 'Bvlgari', name: 'Man Glacial Essence',
    price: 11900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Можжевельник', 'Бергамот'], heart: ['Имбирь', 'Ирис'], base: ['Сандал', 'Клирвуд'] },
    longevityHours: 7, sillage: 3, accords: ['свежий', 'фужерный', 'древесный'],
    desc: 'Ледяной можжевельник и имбирь — арктическая свежесть в исполнении Альберто Морильяса.',
    accent: '#A8C6D4',
  },
  {
    slug: 'bvlgari-omnia-crystalline', brand: 'Bvlgari', name: 'Omnia Crystalline',
    price: 9400, volume: 65, concentration: 'Eau de Toilette', gender: 'ж', tags: [],
    notes: { top: ['Бамбук', 'Груша'], heart: ['Лотос', 'Чай'], base: ['Мускус', 'Гваяк'] },
    longevityHours: 6, sillage: 2, accords: ['цветочный', 'акватический', 'свежий'],
    desc: 'Прозрачный лотос и бамбук — хрустальная лёгкость, которая никогда не бывает «слишком».',
    accent: '#DCE9EE',
  },
  {
    slug: 'bvlgari-omnia-amethyste', brand: 'Bvlgari', name: 'Omnia Amethyste',
    price: 9200, volume: 65, concentration: 'Eau de Toilette', gender: 'ж', tags: [],
    notes: { top: ['Грейпфрут', 'Зелёные ноты'], heart: ['Ирис', 'Болгарская роза'], base: ['Гелиотроп', 'Древесные ноты'] },
    longevityHours: 6, sillage: 2, accords: ['цветочный', 'пудровый', 'свежий'],
    desc: 'Ирис и роза в аметистовой дымке — деликатный шлейф с весны до осени.',
    accent: '#9B7BB8',
  },
  {
    slug: 'bvlgari-rose-goldea', brand: 'Bvlgari', name: 'Rose Goldea',
    price: 14900, volume: 90, concentration: 'Eau de Parfum', gender: 'ж', tags: ['хит'],
    notes: { top: ['Гранат', 'Бергамот'], heart: ['Дамасская роза', 'Пион', 'Жасмин'], base: ['Мускус', 'Сандал', 'Ладан'] },
    longevityHours: 8, sillage: 3, accords: ['цветочный', 'мускусный', 'сладкий'],
    desc: 'Золотая роза с гранатом — главный женский бестселлер ювелирного дома.',
    accent: '#E8B4C8',
  },
  {
    slug: 'bvlgari-goldea-the-roman-night', brand: 'Bvlgari', name: 'Goldea The Roman Night',
    price: 13400, volume: 90, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Шелковица', 'Чёрный перец'], heart: ['Жасмин', 'Пион', 'Тубероза'], base: ['Чёрный мускус', 'Пачули', 'Ветивер'] },
    longevityHours: 7, sillage: 3, accords: ['шипровый', 'цветочный', 'мускусный'],
    desc: 'Ночной Рим во флаконе: тёмный мускус, жасмин и шелковица для выхода в свет.',
    accent: '#2B2140',
  },
  {
    slug: 'bvlgari-jasmin-noir', brand: 'Bvlgari', name: 'Jasmin Noir',
    price: 15400, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Гардения', 'Зелёные ноты'], heart: ['Жасмин самбак', 'Миндаль'], base: ['Лакрица', 'Ценная древесина', 'Бобы тонка'] },
    longevityHours: 8, sillage: 3, accords: ['цветочный', 'древесный', 'сладкий'],
    desc: 'Тёмный жасмин с лакрицей — соблазнительная вечерняя вуаль, ставшая культовой.',
    accent: '#1C1A1D',
  },
  {
    slug: 'bvlgari-pour-homme-soir', brand: 'Bvlgari', name: 'Bvlgari Pour Homme Soir',
    price: 17900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Чай дарджилинг'], heart: ['Папирус', 'Древесные ноты'], base: ['Амбра', 'Мускус'] },
    longevityHours: 7, sillage: 2, accords: ['древесный', 'мускусный', 'свежий'],
    desc: 'Вечерний чай дарджилинг и папирус — снятый с производства культ, который ищут коллекционеры.',
    accent: '#4A4E57',
  },

  // ─── Clive Christian ──────────────────────────────────────
  {
    slug: 'clive-christian-no-1-for-men', brand: 'Clive Christian', name: 'No. 1 For Men',
    price: 89000, volume: 50, concentration: 'Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Лайм', 'Бергамот', 'Кардамон'], heart: ['Мускатный орех', 'Ирис'], base: ['Выдержанный сандал', 'Мускус', 'Кедр'] },
    longevityHours: 12, sillage: 4, accords: ['древесный', 'пряный', 'амбра'],
    desc: 'Легендарный «аромат миллионеров»: 50-летний сандал и безупречный британский лоск.',
    accent: '#C9A227',
  },
  {
    slug: 'clive-christian-no-1-for-women', brand: 'Clive Christian', name: 'No. 1 For Women',
    price: 88000, volume: 50, concentration: 'Parfum', gender: 'ж', tags: [],
    notes: { top: ['Бергамот', 'Персик', 'Кардамон'], heart: ['Ирис', 'Роза', 'Иланг-иланг'], base: ['Сандал', 'Бобы тонка', 'Мускус'] },
    longevityHours: 12, sillage: 4, accords: ['цветочный', 'пудровый', 'восточный'],
    desc: 'Свадебный парфюм Кэти Холмс: масляный ирис и роза в самом дорогом флаконе Британии.',
    accent: '#DDB24A',
  },
  {
    slug: 'clive-christian-x-for-men', brand: 'Clive Christian', name: 'X For Men',
    price: 64000, volume: 50, concentration: 'Parfum', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Кардамон'], heart: ['Жасмин', 'Корица'], base: ['Ветивер', 'Дубовый мох', 'Мускус'] },
    longevityHours: 10, sillage: 4, accords: ['восточный', 'древесный', 'пряный'],
    desc: 'Самый чувственный мужской Clive Christian: специи, жасмин и мох на 20% парфюмерного масла.',
    accent: '#6E1F2E',
  },
  {
    slug: 'clive-christian-x-for-women', brand: 'Clive Christian', name: 'X For Women',
    price: 62000, volume: 50, concentration: 'Parfum', gender: 'ж', tags: [],
    notes: { top: ['Персик', 'Ревень'], heart: ['Египетский жасмин', 'Гардения'], base: ['Пачули', 'Ваниль', 'Мускус'] },
    longevityHours: 10, sillage: 4, accords: ['шипровый', 'фруктовый', 'мускусный'],
    desc: 'Сочный персик на землистой шипровой базе — глубокий люкс без банальностей.',
    accent: '#8C2F4F',
  },
  {
    slug: 'clive-christian-1872-for-men', brand: 'Clive Christian', name: '1872 For Men',
    price: 59000, volume: 50, concentration: 'Parfum', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Лимон', 'Петигрен'], heart: ['Шалфей', 'Розмарин'], base: ['Ветивер', 'Кедр', 'Мускус'] },
    longevityHours: 9, sillage: 3, accords: ['цитрусовый', 'фужерный', 'древесный'],
    desc: 'Хрустящий цитрус на благородном дереве — британская свежесть по рецепту 1872 года.',
    accent: '#2E5E4E',
  },
  {
    slug: 'clive-christian-c-for-men', brand: 'Clive Christian', name: 'C For Men',
    price: 67000, volume: 50, concentration: 'Parfum', gender: 'м', tags: [],
    notes: { top: ['Зелёные листья', 'Лимон'], heart: ['Жасмин', 'Роза'], base: ['Уд', 'Амбра', 'Бобы тонка'] },
    longevityHours: 11, sillage: 4, accords: ['восточный', 'уд', 'древесный'],
    desc: 'Уд, амбра и тонка под строгим смокингом — восточная мощь с британскими манерами.',
    accent: '#3B2F2F',
  },

  // ─── Amouage ──────────────────────────────────────────────
  {
    slug: 'amouage-jubilation-xxv-man', brand: 'Amouage', name: 'Jubilation XXV Man',
    price: 36900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Ежевика', 'Ладан', 'Кориандр'], heart: ['Мёд', 'Корица', 'Роза'], base: ['Уд', 'Мирра', 'Пачули'] },
    longevityHours: 10, sillage: 4, accords: ['восточный', 'медовый', 'дымный'],
    desc: 'Юбилейный шедевр Бертрана Дюшофура: ежевика, мёд и ладан — король восточной парфюмерии.',
    accent: '#7A1F2B',
  },
  {
    slug: 'amouage-jubilation-25-woman', brand: 'Amouage', name: 'Jubilation 25 Woman',
    price: 36500, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Иланг-иланг', 'Роза', 'Лимон'], heart: ['Ладан', 'Лабданум', 'Полынь'], base: ['Мирра', 'Амбра', 'Пачули'] },
    longevityHours: 10, sillage: 4, accords: ['шипровый', 'восточный', 'цветочный'],
    desc: 'Винтажный французский шик: роза, ладан и мирра в честь 25-летия дома.',
    accent: '#A67C00',
  },
  {
    slug: 'amouage-epic-man', brand: 'Amouage', name: 'Epic Man',
    price: 33900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Розовый перец', 'Кардамон', 'Шафран'], heart: ['Ладан', 'Герань'], base: ['Сандал', 'Пачули', 'Кедр'] },
    longevityHours: 9, sillage: 4, accords: ['восточный', 'пряный', 'древесный'],
    desc: 'Путешествие по Шёлковому пути: специи, ладан и дерево — тихая роскошь для уверенных.',
    accent: '#4B3621',
  },
  {
    slug: 'amouage-epic-woman', brand: 'Amouage', name: 'Epic Woman',
    price: 33500, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Корица', 'Тмин', 'Олеандр'], heart: ['Дамасская роза', 'Чай', 'Жасмин'], base: ['Уд', 'Ладан', 'Ваниль', 'Амбра'] },
    longevityHours: 9, sillage: 4, accords: ['восточный', 'цветочный', 'уд'],
    desc: 'Роза и пачули на дымном уде — эпос о сильной женщине.',
    accent: '#6B2D5C',
  },
  {
    slug: 'amouage-memoir-man', brand: 'Amouage', name: 'Memoir Man',
    price: 32900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Абсент', 'Полынь', 'Мята'], heart: ['Роза', 'Ладан', 'Лаванда'], base: ['Кожа', 'Табак', 'Дубовый мох'] },
    longevityHours: 9, sillage: 4, accords: ['дымный', 'кожаный', 'фужерный'],
    desc: 'Абсент, ладан и кожа — тёмный интеллектуальный аромат для тех, кто не боится взглядов.',
    accent: '#23282B',
  },
  {
    slug: 'amouage-memoir-woman', brand: 'Amouage', name: 'Memoir Woman',
    price: 32500, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Полынь', 'Кардамон', 'Мандарин'], heart: ['Ладан', 'Гвоздика', 'Белые цветы'], base: ['Кожа', 'Лабданум', 'Дубовый мох'] },
    longevityHours: 9, sillage: 4, accords: ['шипровый', 'кожаный', 'дымный'],
    desc: 'Готическая красавица: белые цветы, ладан и кожа — глубоко, зрело, незабываемо.',
    accent: '#1B1B24',
  },
  {
    slug: 'amouage-honour-woman', brand: 'Amouage', name: 'Honour Woman',
    price: 31900, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Перец', 'Ревень', 'Кориандр'], heart: ['Тубероза', 'Жасмин', 'Гардения'], base: ['Ладан', 'Ветивер', 'Амбра'] },
    longevityHours: 8, sillage: 3, accords: ['цветочный', 'восточный'],
    desc: 'Самый деликатный Amouage: сияющие тубероза и жасмин по мотивам «Мадам Баттерфляй».',
    accent: '#EFE7D8',
  },
  {
    slug: 'amouage-lyric-woman', brand: 'Amouage', name: 'Lyric Woman',
    price: 34900, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Бергамот', 'Корица', 'Имбирь'], heart: ['Роза', 'Иланг-иланг', 'Ангелика'], base: ['Ладан', 'Сандал', 'Бобы тонка'] },
    longevityHours: 9, sillage: 4, accords: ['восточный', 'цветочный', 'пряный'],
    desc: 'Бархатная тёмно-красная роза со специями — ода женственности от оманского дома.',
    accent: '#7B1E3B',
  },
  {
    slug: 'amouage-gold-woman', brand: 'Amouage', name: 'Gold Woman',
    price: 35900, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Альдегиды', 'Роза'], heart: ['Ландыш', 'Жасмин'], base: ['Серая амбра', 'Мускус', 'Сандал'] },
    longevityHours: 9, sillage: 4, accords: ['цветочный', 'пудровый', 'мускусный'],
    desc: 'Первый аромат дома (1983): альдегидные цветы и серая амбра — парфюмерное золото Омана.',
    accent: '#D4A017',
  },
  {
    slug: 'amouage-interlude-woman', brand: 'Amouage', name: 'Interlude Woman',
    price: 34500, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Бергамот', 'Имбирь', 'Бархатцы'], heart: ['Ладан', 'Мёд', 'Кофе'], base: ['Уд', 'Кожа', 'Ваниль'] },
    longevityHours: 10, sillage: 4, accords: ['восточный', 'медовый', 'дымный'],
    desc: 'Хаос, превращённый в гармонию: мёд, кофе и ладан в полуночно-синем хрустале.',
    accent: '#1F2A6B',
  },
  {
    slug: 'amouage-reflection-woman', brand: 'Amouage', name: 'Reflection Woman',
    price: 31500, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Фрезия', 'Зелёные листья'], heart: ['Магнолия', 'Жасмин'], base: ['Кедр', 'Сандал', 'Амбра'] },
    longevityHours: 7, sillage: 3, accords: ['цветочный', 'свежий'],
    desc: 'Акварельная магнолия Мориса Руселя — светлая женская пара культового Reflection.',
    accent: '#C9D8E8',
  },
  {
    slug: 'amouage-guidance', brand: 'Amouage', name: 'Guidance',
    price: 37900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит', 'новинка'],
    notes: { top: ['Груша', 'Розовая вода', 'Ладан'], heart: ['Роза', 'Османтус', 'Шафран'], base: ['Сандал', 'Амбра', 'Ваниль'] },
    longevityHours: 12, sillage: 5, accords: ['восточный', 'цветочный', 'сладкий'],
    desc: 'Бестселлер новой эры Amouage: сочная груша, роза и ладан с ядерным шлейфом.',
    accent: '#E5C687',
  },

  // ─── Roja Parfums ─────────────────────────────────────────
  {
    slug: 'roja-elysium-pour-homme', brand: 'Roja Parfums', name: 'Elysium Pour Homme',
    price: 42900, volume: 100, concentration: 'Parfum Cologne', gender: 'м', tags: ['хит'],
    notes: { top: ['Грейпфрут', 'Лимон', 'Полынь'], heart: ['Яблоко', 'Ландыш', 'Розовый перец'], base: ['Серая амбра', 'Кожа', 'Ваниль'] },
    longevityHours: 8, sillage: 3, accords: ['цитрусовый', 'свежий', 'фужерный'],
    desc: 'Эталон люксовой свежести: цитрус на серой амбре из безупречных материалов Roja Dove.',
    accent: '#1F4FA0',
  },
  {
    slug: 'roja-enigma-pour-homme', brand: 'Roja Parfums', name: 'Enigma Pour Homme',
    price: 44900, volume: 100, concentration: 'Parfum Cologne', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Нероли'], heart: ['Гелиотроп', 'Жасмин', 'Герань'], base: ['Коньяк', 'Табак', 'Ваниль'] },
    longevityHours: 9, sillage: 4, accords: ['табачный', 'сладкий', 'восточный'],
    desc: 'Коньяк, табак и ваниль — знаменитая «кола» Roja, вечерняя классика для смокинга.',
    accent: '#5C3317',
  },
  {
    slug: 'roja-danger-pour-homme', brand: 'Roja Parfums', name: 'Danger Pour Homme',
    price: 51900, volume: 50, concentration: 'Parfum', gender: 'м', tags: [],
    notes: { top: ['Лаванда', 'Бергамот', 'Эстрагон'], heart: ['Фиалка', 'Жасмин', 'Ландыш'], base: ['Дубовый мох', 'Кожа', 'Бобы тонка'] },
    longevityHours: 9, sillage: 4, accords: ['фужерный', 'кожаный', 'шипровый'],
    desc: 'Опасная классика старой школы: лаванда и кожа на замшелой базе-афродизиаке.',
    accent: '#8B0000',
  },
  {
    slug: 'roja-amber-aoud', brand: 'Roja Parfums', name: 'Amber Aoud',
    price: 59900, volume: 100, concentration: 'Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Бергамот', 'Лайм'], heart: ['Роза', 'Инжир', 'Иланг-иланг'], base: ['Уд', 'Шафран', 'Амбра', 'Сандал'] },
    longevityHours: 12, sillage: 5, accords: ['уд', 'амбра', 'пряный'],
    desc: 'Роза, шафран и уд — легендарный восточный флагман Roja с монструозным шлейфом.',
    accent: '#B45309',
  },
  {
    slug: 'roja-scandal-pour-homme', brand: 'Roja Parfums', name: 'Scandal Pour Homme',
    price: 43900, volume: 100, concentration: 'Parfum Cologne', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Лимон'], heart: ['Жасмин', 'Роза', 'Ландыш'], base: ['Дубовый мох', 'Ветивер', 'Амбра'] },
    longevityHours: 8, sillage: 3, accords: ['шипровый', 'цитрусовый', 'мускусный'],
    desc: 'Шипровая элегантность старой школы — скандально хорош на выход и переговоры.',
    accent: '#333B2F',
  },
  {
    slug: 'roja-apex', brand: 'Roja Parfums', name: 'Apex',
    price: 49900, volume: 100, concentration: 'Parfum', gender: 'у', tags: ['новинка'],
    notes: { top: ['Ананас', 'Бергамот', 'Мандарин'], heart: ['Жасмин', 'Лабданум'], base: ['Кожа', 'Дубовый мох', 'Табак', 'Ром'] },
    longevityHours: 11, sillage: 4, accords: ['фруктовый', 'кожаный', 'шипровый'],
    desc: 'Ананас на коже и мхе — хищный современный шипр, который держится сутки.',
    accent: '#14532D',
  },
];
