import type { RawProduct } from '../products';

/* ─── НИША 2: Parfums de Marly, Xerjoff, Initio, Nishane, Mancera, Montale ─── */
export const SEG_NICHE_2: RawProduct[] = [
  /* ── Parfums de Marly ── */
  {
    slug: 'pdm-althair', brand: 'Parfums de Marly', name: 'Althaïr',
    price: 29900, volume: 125, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Бергамот', 'Апельсиновый цвет', 'Корица', 'Кардамон'], heart: ['Бурбонская ваниль', 'Элеми'], base: ['Пралине', 'Гваяковое дерево', 'Амброксан', 'Мускус'] },
    longevityHours: 10, sillage: 4, accords: ['ваниль', 'пряный', 'сладкий'],
    desc: 'Мадагаскарская ваниль с корицей и пралине — аромат, который женщины признали самым притягательным мужским парфюмом года.',
    accent: '#D2A24C',
  },
  {
    slug: 'pdm-carlisle', brand: 'Parfums de Marly', name: 'Carlisle',
    price: 30000, volume: 125, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Бергамот', 'Мандарин'], heart: ['Фиалка', 'Жасмин', 'Ваниль'], base: ['Гваяковое дерево', 'Пачули', 'Кардамон'] },
    longevityHours: 12, sillage: 5, accords: ['сладкий', 'древесный', 'пудровый'],
    desc: 'Королевская ваниль на дорогих породах дерева: густой шлейф, который окружающие запоминают надолго.',
    accent: '#8C6239',
  },
  {
    slug: 'pdm-percival', brand: 'Parfums de Marly', name: 'Percival',
    price: 26900, volume: 125, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Лимон', 'Лаванда'], heart: ['Роза', 'Герань', 'Корица'], base: ['Амброксан', 'Кашмеран', 'Мускус'] },
    longevityHours: 8, sillage: 4, accords: ['свежий', 'фужерный', 'пряный'],
    desc: 'Благородная свежесть рыцаря Круглого стола — безотказный аромат для офиса и свиданий в любое время года.',
    accent: '#3F6FB5',
  },
  {
    slug: 'pdm-sedley', brand: 'Parfums de Marly', name: 'Sedley',
    price: 25900, volume: 125, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Бергамот', 'Мята', 'Водные ноты'], heart: ['Лаванда', 'Герань', 'Яблоко'], base: ['Сандал', 'Ветивер', 'Мускус'] },
    longevityHours: 8, sillage: 3, accords: ['свежий', 'акватический', 'фужерный'],
    desc: 'Ледяная мята с сандалом — самый искристый и летний Marly, свежесть которого слышно весь день.',
    accent: '#4FA3C7',
  },
  {
    slug: 'pdm-haltane', brand: 'Parfums de Marly', name: 'Haltane',
    price: 29900, volume: 125, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Шафран', 'Лаванда'], heart: ['Уд', 'Пралине'], base: ['Пачули', 'Кедр', 'Ветивер'] },
    longevityHours: 12, sillage: 4, accords: ['уд', 'древесный', 'сладкий'],
    desc: 'Полированный уд с пралине, созданный для Harrods: строгая роскошь без единой лишней ноты.',
    accent: '#5B4632',
  },
  {
    slug: 'pdm-kalan', brand: 'Parfums de Marly', name: 'Kalan',
    price: 25900, volume: 125, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Красный апельсин', 'Чёрный перец'], heart: ['Лаванда', 'Флёрдоранж'], base: ['Амбра', 'Бобы тонка', 'Сандал', 'Мох'] },
    longevityHours: 10, sillage: 4, accords: ['пряный', 'амбра', 'цитрусовый'],
    desc: 'Искрящийся красный апельсин на тёплой амбре — аромат, который лучше всего звучит в шлейфе.',
    accent: '#C0392B',
  },
  {
    slug: 'pdm-godolphin', brand: 'Parfums de Marly', name: 'Godolphin',
    price: 25900, volume: 125, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Кипарис', 'Роза'], heart: ['Кожа', 'Ирис', 'Жасмин'], base: ['Уд', 'Ветивер', 'Амбра'] },
    longevityHours: 9, sillage: 3, accords: ['кожаный', 'древесный', 'уд'],
    desc: 'Выделанная кожа и роза в честь легендарного жеребца — аристократичная классика для ценителей.',
    accent: '#6B4A2F',
  },
  {
    slug: 'pdm-valaya', brand: 'Parfums de Marly', name: 'Valaya',
    price: 27900, volume: 75, concentration: 'Eau de Parfum', gender: 'ж', tags: ['новинка'],
    notes: { top: ['Альдегиды', 'Белый персик', 'Бергамот'], heart: ['Флёрдоранж', 'Ландыш'], base: ['Белый мускус', 'Амброксан', 'Ваниль'] },
    longevityHours: 8, sillage: 3, accords: ['мускусный', 'цветочный', 'свежий'],
    desc: 'Ощущение свежего хлопка на коже: чистый, светящийся аромат от автора Delina — Кантена Биша.',
    accent: '#C8B896',
  },

  /* ── Xerjoff ── */
  {
    slug: 'xerjoff-alexandria-ii', brand: 'Xerjoff', name: 'Alexandria II',
    price: 44900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Розовое дерево', 'Лаванда', 'Яблоко', 'Корица'], heart: ['Роза', 'Кедр', 'Ландыш'], base: ['Уд', 'Сандал', 'Ваниль', 'Амбра'] },
    longevityHours: 14, sillage: 5, accords: ['уд', 'древесный', 'сладкий'],
    desc: 'Легенда нишевой парфюмерии: бархатный уд с розой и ванилью, который держится на коже больше суток.',
    accent: '#B8860B',
  },
  {
    slug: 'xerjoff-1861-renaissance', brand: 'Xerjoff', name: 'XJ 1861 Renaissance',
    price: 39900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Мандарин', 'Бергамот', 'Лимон'], heart: ['Болгарская роза', 'Ландыш', 'Мята'], base: ['Пачули', 'Кедр', 'Амбра', 'Мускус'] },
    longevityHours: 10, sillage: 3, accords: ['цитрусовый', 'свежий', 'древесный'],
    desc: 'Итальянский лимон на ложе из мяты и ландыша — цитрус люксового уровня с невероятной стойкостью.',
    accent: '#3A7D44',
  },
  {
    slug: 'xerjoff-accento', brand: 'Xerjoff', name: 'Accento',
    price: 34900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Ананас', 'Гиацинт'], heart: ['Ирис', 'Розовый перец', 'Жасмин'], base: ['Мускус', 'Амбра', 'Ветивер', 'Ваниль'] },
    longevityHours: 10, sillage: 4, accords: ['фруктовый', 'цветочный', 'шипровый'],
    desc: 'Сияющий ананас с ирисом — элегантный и лёгкий Xerjoff, который уместен всегда и везде.',
    accent: '#4169E1',
  },
  {
    slug: 'xerjoff-lira', brand: 'Xerjoff', name: 'Lira',
    price: 28900, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: ['хит'],
    notes: { top: ['Бергамот', 'Красный апельсин', 'Лаванда'], heart: ['Корица', 'Жасмин'], base: ['Ваниль', 'Карамель', 'Мускус', 'Лакрица'] },
    longevityHours: 8, sillage: 4, accords: ['гурманский', 'сладкий', 'цитрусовый'],
    desc: 'Лимонный десерт с карамелью и корицей — эталонный гурманский аромат, собирающий комплименты за секунды.',
    accent: '#E2953F',
  },
  {
    slug: 'xerjoff-italica', brand: 'Xerjoff', name: 'Italica',
    price: 29900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Молоко', 'Миндаль', 'Шафран'], heart: ['Ириска', 'Бурбонская ваниль', 'Флёрдоранж'], base: ['Сандал', 'Белый мускус', 'Бобы тонка'] },
    longevityHours: 9, sillage: 4, accords: ['гурманский', 'сладкий', 'пудровый'],
    desc: 'Миндальное печенье амаретти в молочно-сливочной дымке — самый уютный гурман итальянского дома.',
    accent: '#DDB77C',
  },
  {
    slug: 'xerjoff-nio', brand: 'Xerjoff', name: 'Nio',
    price: 38900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Зелёные ноты', 'Нероли'], heart: ['Кардамон', 'Розовый перец', 'Мускатный орех'], base: ['Ветивер', 'Кедр', 'Амбра', 'Пачули'] },
    longevityHours: 8, sillage: 3, accords: ['цитрусовый', 'пряный', 'древесный'],
    desc: 'Самый реалистичный бергамот на рынке: прогулка по итальянскому побережью в хрустальном флаконе.',
    accent: '#5A7D9A',
  },
  {
    slug: 'xerjoff-uden', brand: 'Xerjoff', name: 'Uden',
    price: 37900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Лимон', 'Грейпфрут'], heart: ['Ром', 'Гваяковое дерево', 'Сандал', 'Роза'], base: ['Кофе', 'Ваниль', 'Мускус', 'Амбра'] },
    longevityHours: 8, sillage: 3, accords: ['цитрусовый', 'кофейный', 'сладкий'],
    desc: 'Цитрус, переходящий в кофе с ромом: редкий аромат, который свежий и тёплый одновременно.',
    accent: '#2E6B4F',
  },
  {
    slug: 'xerjoff-more-than-words', brand: 'Xerjoff', name: 'More Than Words',
    price: 42900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Фруктовые ноты', 'Шафран'], heart: ['Роза', 'Уд'], base: ['Амбра', 'Мускус', 'Древесные ноты'] },
    longevityHours: 14, sillage: 5, accords: ['уд', 'фруктовый', 'амбра'],
    desc: 'Фруктовая роза на уде с лучшей стойкостью во всей линейке Xerjoff — шлейф на 20 часов и больше.',
    accent: '#34495E',
  },
  {
    slug: 'xerjoff-soprano', brand: 'Xerjoff', name: 'Soprano',
    price: 35900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Личи', 'Бергамот'], heart: ['Роза', 'Жасмин', 'Молочные ноты'], base: ['Уд', 'Пачули', 'Кожа'] },
    longevityHours: 10, sillage: 4, accords: ['фруктовый', 'цветочный', 'уд'],
    desc: 'Сочное личи и сливочная роза на кожаной базе — оперная драма, к флакону которой прилагается шёлковый платок.',
    accent: '#D96A8B',
  },
  {
    slug: 'xerjoff-golden-dallah', brand: 'Xerjoff', name: 'Golden Dallah',
    price: 44900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Экзотические специи', 'Кардамон'], heart: ['Ладан', 'Кофе', 'Камбоджийский уд', 'Роза'], base: ['Какао', 'Фундук', 'Бобы тонка'] },
    longevityHours: 12, sillage: 4, accords: ['кофейный', 'восточный', 'гурманский'],
    desc: 'Арабский кофе с ладаном и удом: густой восточный вечерний аромат для тех, кто не хочет быть как все.',
    accent: '#A67C00',
  },

  /* ── Initio ── */
  {
    slug: 'initio-rehab', brand: 'Initio', name: 'Rehab',
    price: 31900, volume: 90, concentration: 'Extrait de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Лаванда', 'Бергамот'], heart: ['Табак', 'Сандал'], base: ['Ваниль', 'Мускус', 'Бобы тонка'] },
    longevityHours: 8, sillage: 3, accords: ['табачный', 'древесный', 'сладкий'],
    desc: 'Сливочный табак с сандалом от автора культового Herod — обволакивающий аромат-антистресс.',
    accent: '#7D5A3C',
  },
  {
    slug: 'initio-musk-therapy', brand: 'Initio', name: 'Musk Therapy',
    price: 30900, volume: 90, concentration: 'Extrait de Parfum', gender: 'у', tags: [],
    notes: { top: ['Бергамот', 'Чёрная смородина', 'Мандарин'], heart: ['Магнолия', 'Белый мускус'], base: ['Мускус', 'Сандал'] },
    longevityHours: 8, sillage: 3, accords: ['мускусный', 'свежий', 'цветочный'],
    desc: 'Идеально чистая кожа и свежее бельё: терапия белым мускусом, к которой хочется прижаться.',
    accent: '#9BB7D4',
  },
  {
    slug: 'initio-atomic-rose', brand: 'Initio', name: 'Atomic Rose',
    price: 32900, volume: 90, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Бергамот', 'Гедион'], heart: ['Турецкая роза', 'Болгарская роза'], base: ['Амброксан', 'Ваниль'] },
    longevityHours: 10, sillage: 4, accords: ['цветочный', 'амбра', 'сладкий'],
    desc: 'Роза во взрывной атомной подаче: один пшик заполняет комнату и держится до самого вечера.',
    accent: '#D8365D',
  },
  {
    slug: 'initio-paragon', brand: 'Initio', name: 'Paragon',
    price: 33900, volume: 90, concentration: 'Extrait de Parfum', gender: 'у', tags: [],
    notes: { top: ['Шалфей', 'Лаванда', 'Бергамот'], heart: ['Слива', 'Пало санто', 'Чёрный перец'], base: ['Сандал', 'Уд'] },
    longevityHours: 10, sillage: 4, accords: ['древесный', 'пряный', 'дымный'],
    desc: 'Медитативное пало санто с шалфеем и сливой — спокойная сила, которую окружающие считывают безошибочно.',
    accent: '#4E5D4A',
  },
  {
    slug: 'initio-blessed-baraka', brand: 'Initio', name: 'Blessed Baraka',
    price: 30900, volume: 90, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Белые цветы', 'Бергамот'], heart: ['Сандал', 'Амбра'], base: ['Ваниль', 'Мускус'] },
    longevityHours: 9, sillage: 3, accords: ['амбра', 'древесный', 'сладкий'],
    desc: 'Гладкий сандал в янтарном сиропе с вишнёвой иллюзией — тихая роскошь, притягивающая ближе.',
    accent: '#C29B4A',
  },
  {
    slug: 'initio-psychedelic-love', brand: 'Initio', name: 'Psychedelic Love',
    price: 31900, volume: 90, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Бергамот', 'Иланг-иланг'], heart: ['Гелиотроп', 'Роза', 'Гедион'], base: ['Амбра', 'Пралине', 'Мускус'] },
    longevityHours: 9, sillage: 3, accords: ['цветочный', 'пудровый', 'сладкий'],
    desc: 'Пудровый гелиотроп с розой и пралине — гипнотический аромат-приворот для взрослых романов.',
    accent: '#D4547A',
  },

  /* ── Nishane ── */
  {
    slug: 'nishane-wulong-cha', brand: 'Nishane', name: 'Wulong Cha',
    price: 23900, volume: 100, concentration: 'Extrait de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Бергамот', 'Мандарин', 'Литсея кубеба'], heart: ['Чай улун', 'Мускатный орех'], base: ['Инжир', 'Мускус'] },
    longevityHours: 6, sillage: 2, accords: ['свежий', 'зелёный', 'цитрусовый'],
    desc: 'Холодный чай улун с цитрусами — самый освежающий нишевый аромат для жары и чистых рубашек.',
    accent: '#7FA65A',
  },
  {
    slug: 'nishane-ege', brand: 'Nishane', name: 'Ege',
    price: 24900, volume: 100, concentration: 'Extrait de Parfum', gender: 'у', tags: [],
    notes: { top: ['Юдзу', 'Листья фиалки', 'Анис'], heart: ['Базилик', 'Кардамон', 'Мята'], base: ['Ладан', 'Лакрица'] },
    longevityHours: 7, sillage: 3, accords: ['акватический', 'свежий', 'зелёный'],
    desc: 'Бриз Эгейского моря во флаконе: юдзу, мята и базилик уносят в отпуск с первого распыления.',
    accent: '#2E9CCA',
  },
  {
    slug: 'nishane-hundred-silent-ways', brand: 'Nishane', name: 'Hundred Silent Ways',
    price: 26900, volume: 100, concentration: 'Extrait de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Тубероза', 'Персик', 'Мандарин'], heart: ['Гардения', 'Жасмин', 'Ирис'], base: ['Ваниль', 'Сандал', 'Ветивер'] },
    longevityHours: 10, sillage: 4, accords: ['цветочный', 'сладкий', 'пудровый'],
    desc: 'Персик и кремовая тубероза по мотивам Руми — бестселлер Nishane, признание в любви без слов.',
    accent: '#DE9FB8',
  },
  {
    slug: 'nishane-fan-your-flames', brand: 'Nishane', name: 'Fan Your Flames',
    price: 25900, volume: 100, concentration: 'Extrait de Parfum', gender: 'у', tags: [],
    notes: { top: ['Кокос', 'Ром', 'Мастика'], heart: ['Табак', 'Бобы тонка', 'Тимьян'], base: ['Дубовый мох', 'Пачули', 'Кедр'] },
    longevityHours: 10, sillage: 4, accords: ['табачный', 'гурманский', 'древесный'],
    desc: 'Ром, кокос и табак — дерзкий вечерний аромат для тех, кто разжигает пламя, а не греется у чужого.',
    accent: '#C75B12',
  },
  {
    slug: 'nishane-vain-naive', brand: 'Nishane', name: 'Vain & Naïve',
    price: 22900, volume: 100, concentration: 'Extrait de Parfum', gender: 'у', tags: [],
    notes: { top: ['Апельсин', 'Бергамот'], heart: ['Малина', 'Слива', 'Роза'], base: ['Сандал', 'Бобы тонка', 'Бензоин', 'Мускус'] },
    longevityHours: 8, sillage: 3, accords: ['фруктовый', 'сладкий', 'цветочный'],
    desc: 'Сочная малина со сливой на тёплом сандале — беззаботный и обаятельный аромат хорошего настроения.',
    accent: '#C94F7C',
  },
  {
    slug: 'nishane-sultan-vetiver', brand: 'Nishane', name: 'Sultan Vetiver',
    price: 21900, volume: 100, concentration: 'Extrait de Parfum', gender: 'у', tags: [],
    notes: { top: ['Ветивер', 'Анис', 'Бергамот', 'Перец'], heart: ['Нероли', 'Бобы тонка'], base: ['Кожа', 'Амбра'] },
    longevityHours: 8, sillage: 3, accords: ['зелёный', 'древесный', 'кожаный'],
    desc: 'Три сорта ветивера в одном флаконе: эталонная зелёная классика для ценителей строгих ароматов.',
    accent: '#556B2F',
  },
  {
    slug: 'nishane-nefs', brand: 'Nishane', name: 'Nefs',
    price: 27900, volume: 50, concentration: 'Extrait de Parfum', gender: 'у', tags: [],
    notes: { top: ['Мёд', 'Шафран', 'Инжир'], heart: ['Роза', 'Османтус', 'Мускатный орех'], base: ['Уд', 'Виски', 'Ваниль', 'Кожа'] },
    longevityHours: 12, sillage: 5, accords: ['медовый', 'восточный', 'уд'],
    desc: 'Мёд, виски и уд — один из самых роскошных нишевых ароматов вообще, создан для особенных вечеров.',
    accent: '#8B1E3F',
  },
  {
    slug: 'nishane-tuberoza', brand: 'Nishane', name: 'Tuberoza',
    price: 22900, volume: 100, concentration: 'Extrait de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Иланг-иланг', 'Флёрдоранж', 'Полынь'], heart: ['Тубероза', 'Гардения', 'Жасмин'], base: ['Ветивер', 'Мускус', 'Амбра', 'Сандал'] },
    longevityHours: 8, sillage: 4, accords: ['цветочный', 'мускусный'],
    desc: 'Опьяняющая белоцветочная тубероза с гарденией — женственная классика в стамбульском прочтении.',
    accent: '#C9BC9C',
  },

  /* ── Mancera ── */
  {
    slug: 'mancera-roses-vanille', brand: 'Mancera', name: 'Roses Vanille',
    price: 15900, volume: 120, concentration: 'Eau de Parfum', gender: 'ж', tags: ['хит'],
    notes: { top: ['Итальянский лимон', 'Сахарная пудра'], heart: ['Турецкая роза', 'Рахат-лукум'], base: ['Ваниль', 'Белый мускус', 'Кедр'] },
    longevityHours: 12, sillage: 5, accords: ['сладкий', 'цветочный', 'ваниль'],
    desc: 'Розовый рахат-лукум с ванилью, который держится сутками, — главный сладкий бестселлер Mancera.',
    accent: '#E85C8F',
  },
  {
    slug: 'mancera-instant-crush', brand: 'Mancera', name: 'Instant Crush',
    price: 16900, volume: 120, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Шафран', 'Имбирь', 'Цитрусы'], heart: ['Белые цветы', 'Амбра'], base: ['Ваниль', 'Сандал', 'Мускус'] },
    longevityHours: 12, sillage: 5, accords: ['амбра', 'сладкий', 'пряный'],
    desc: 'Шафрановая амбра в духе Baccarat Rouge, но глубже и универсальнее — влюбляет с первого вдоха.',
    accent: '#C0182B',
  },
  {
    slug: 'mancera-tonka-cola', brand: 'Mancera', name: 'Tonka Cola',
    price: 15900, volume: 120, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Корица', 'Вишня', 'Сицилийский лимон'], heart: ['Кола', 'Пачули', 'Флёрдоранж'], base: ['Бобы тонка', 'Ваниль', 'Бензоин'] },
    longevityHours: 10, sillage: 4, accords: ['гурманский', 'сладкий', 'пряный'],
    desc: 'Шипучая вишнёвая кола с корицей и бобами тонка — самый весёлый гурман в нашей витрине.',
    accent: '#8B4A2B',
  },
  {
    slug: 'mancera-coco-vanille', brand: 'Mancera', name: 'Coco Vanille',
    price: 15900, volume: 120, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Кокос', 'Тиаре'], heart: ['Иланг-иланг', 'Жасмин'], base: ['Ваниль', 'Мускус', 'Сандал'] },
    longevityHours: 10, sillage: 4, accords: ['ваниль', 'сладкий', 'гурманский'],
    desc: 'Сливочный кокос с ванилью и цветком тиаре: пляжный рай, который остаётся с вами весь день.',
    accent: '#DCC49A',
  },
  {
    slug: 'mancera-aoud-lemon-mint', brand: 'Mancera', name: 'Aoud Lemon Mint',
    price: 14900, volume: 120, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Лимон', 'Миндаль', 'Чёрный перец'], heart: ['Уд', 'Мята', 'Жасмин'], base: ['Ваниль', 'Амбра', 'Ветивер'] },
    longevityHours: 9, sillage: 4, accords: ['цитрусовый', 'свежий', 'уд'],
    desc: 'Ледяной лимон с мятой на мягком уде — свежесть нишевого уровня, которая не сдаётся даже в жару.',
    accent: '#9BC53D',
  },
  {
    slug: 'mancera-hindu-kush', brand: 'Mancera', name: 'Hindu Kush',
    price: 14900, volume: 120, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Ладан', 'Специи', 'Каннабис'], heart: ['Пачули', 'Древесные ноты'], base: ['Амбра', 'Гваяковое дерево', 'Ваниль', 'Белый мускус'] },
    longevityHours: 10, sillage: 4, accords: ['дымный', 'древесный', 'восточный'],
    desc: 'Дымный ладан и пряности горного перевала — характерный аромат для тех, кто ищет необычное.',
    accent: '#4A5D23',
  },
  {
    slug: 'mancera-black-gold', brand: 'Mancera', name: 'Black Gold',
    price: 16900, volume: 120, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Цитрусы', 'Лаванда', 'Корица'], heart: ['Жасмин', 'Фиалка', 'Морские ноты'], base: ['Кожа', 'Ветивер', 'Амбра', 'Мускус'] },
    longevityHours: 10, sillage: 4, accords: ['древесный', 'кожаный', 'свежий'],
    desc: 'Свежесть и сила в чёрно-золотом флаконе: непальский уд, кожа и цитрусы для уверенных мужчин.',
    accent: '#8A7431',
  },
  {
    slug: 'mancera-sicily', brand: 'Mancera', name: 'Sicily',
    price: 13900, volume: 120, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Апельсин', 'Лимон', 'Персик'], heart: ['Жасмин', 'Ландыш'], base: ['Мускус', 'Древесные ноты'] },
    longevityHours: 8, sillage: 3, accords: ['цитрусовый', 'цветочный', 'свежий'],
    desc: 'Стакан сицилийского апельсинового сока и белый жасмин — солнечный отпуск в каждом распылении.',
    accent: '#E8A13D',
  },

  /* ── Montale ── */
  {
    slug: 'montale-black-aoud', brand: 'Montale', name: 'Black Aoud',
    price: 12900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Мандарин', 'Роза'], heart: ['Уд', 'Пачули'], base: ['Мускус', 'Лабданум'] },
    longevityHours: 14, sillage: 5, accords: ['уд', 'цветочный', 'древесный'],
    desc: 'Эталонная тёмная роза на уде: пара капель проецируется 20 часов — легенда, с которой начинают знакомство с удом.',
    accent: '#3B2F2F',
  },
  {
    slug: 'montale-chocolate-greedy', brand: 'Montale', name: 'Chocolate Greedy',
    price: 11900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Какао', 'Апельсин'], heart: ['Сухофрукты', 'Кофе'], base: ['Ваниль', 'Бобы тонка'] },
    longevityHours: 9, sillage: 4, accords: ['гурманский', 'сладкий', 'кофейный'],
    desc: 'Свежеиспечённый брауни и горячий шоколад — самый вкусный способ согреться в холодный день.',
    accent: '#5D3A1A',
  },
  {
    slug: 'montale-roses-musk', brand: 'Montale', name: 'Roses Musk',
    price: 11900, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: ['хит'],
    notes: { top: ['Дамасская роза', 'Зелёные ноты'], heart: ['Жасмин', 'Роза'], base: ['Белый мускус', 'Амбра'] },
    longevityHours: 10, sillage: 4, accords: ['цветочный', 'мускусный'],
    desc: 'Чистая роза на белом мускусе — визитная карточка Montale и один из самых комплиментарных розовых ароматов.',
    accent: '#D6619C',
  },
  {
    slug: 'montale-honey-aoud', brand: 'Montale', name: 'Honey Aoud',
    price: 12900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Мёд', 'Корица'], heart: ['Уд', 'Пачули', 'Цветочные ноты'], base: ['Ваниль', 'Амбра', 'Кожа'] },
    longevityHours: 12, sillage: 5, accords: ['медовый', 'уд', 'сладкий'],
    desc: 'Густой мёд с корицей на лаосском уде — аромат, который слышно на коже даже после душа.',
    accent: '#C68E17',
  },
  {
    slug: 'montale-dark-purple', brand: 'Montale', name: 'Dark Purple',
    price: 11900, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Слива', 'Апельсин'], heart: ['Роза', 'Красные ягоды', 'Пачули'], base: ['Мускус', 'Тиковое дерево', 'Амбра'] },
    longevityHours: 10, sillage: 4, accords: ['фруктовый', 'цветочный', 'мускусный'],
    desc: 'Спелая слива и тёмная роза с сумасшедшей стойкостью — глубокий ягодный аромат на все сезоны.',
    accent: '#5D3A6E',
  },
  {
    slug: 'montale-vanilla-extasy', brand: 'Montale', name: 'Vanilla Extasy',
    price: 10900, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Абрикос', 'Цветы абрикоса'], heart: ['Ваниль', 'Иланг-иланг', 'Жасмин'], base: ['Бензоин', 'Сандал', 'Смолы'] },
    longevityHours: 8, sillage: 3, accords: ['ваниль', 'цветочный', 'сладкий'],
    desc: 'Цветочная ваниль с абрикосом — нежная, не приторная и очень женственная альтернатива сладким гурманам.',
    accent: '#D9BD8B',
  },
  {
    slug: 'montale-fruits-of-the-musk', brand: 'Montale', name: 'Fruits of the Musk',
    price: 10900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Малина', 'Ежевика', 'Бергамот'], heart: ['Роза', 'Листья земляники'], base: ['Мускус', 'Амбра'] },
    longevityHours: 8, sillage: 3, accords: ['фруктовый', 'мускусный'],
    desc: 'Игристые лесные ягоды на фирменном мускусе Montale — лёгкий и звонкий аромат хорошего дня.',
    accent: '#C43E6B',
  },
  {
    slug: 'montale-ristretto-intense-cafe', brand: 'Montale', name: 'Ristretto Intense Café',
    price: 13900, volume: 100, concentration: 'Extrait de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Кофе', 'Турецкая роза'], heart: ['Жареные кофейные зёрна', 'Французская роза', 'Древесные ноты'], base: ['Ваниль', 'Карамель', 'Белый мускус', 'Амбра'] },
    longevityHours: 10, sillage: 4, accords: ['кофейный', 'гурманский', 'сладкий'],
    desc: 'Двойная порция кофе с розой и карамелью в экстракте — маст-хэв для всех кофеманов.',
    accent: '#4B2E20',
  },
];
