import type { RawProduct } from '../products';

/* Сегмент: Kilian, Memo Paris, Penhaligon's, Serge Lutens, Diptyque */
export const SEG_KILIAN: RawProduct[] = [
  /* ─── KILIAN ─── */
  {
    slug: 'kilian-good-girl-gone-bad', brand: 'Kilian', name: 'Good Girl Gone Bad',
    price: 29900, volume: 50, concentration: 'Eau de Parfum', gender: 'ж', tags: ['хит'],
    notes: { top: ['Нероли', 'Османтус'], heart: ['Майская роза', 'Жасмин самбак'], base: ['Нарцисс', 'Амбра', 'Цибетин'] },
    longevityHours: 8, sillage: 4, accords: ['цветочный', 'сладкий', 'мускусный'],
    desc: 'Пышный букет белых цветов с озорным характером — визитная карточка Kilian для женщин, которым скучно быть паиньками.',
    accent: '#D9A86C',
  },
  {
    slug: 'kilian-straight-to-heaven', brand: 'Kilian', name: 'Straight to Heaven, White Cristal',
    price: 28900, volume: 50, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Ром', 'Сухофрукты'], heart: ['Пачули', 'Кедр'], base: ['Амбра', 'Белый мускус', 'Ваниль'] },
    longevityHours: 8, sillage: 3, accords: ['древесный', 'сладкий', 'пряный'],
    desc: 'Выдержанный ром и пачули — мужская классика Kilian, которая пахнет уверенностью и дорогим костюмом.',
    accent: '#6B4A2F',
  },
  {
    slug: 'kilian-intoxicated', brand: 'Kilian', name: 'Intoxicated',
    price: 27900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Кардамон', 'Кофе', 'Бергамот'], heart: ['Мускатный орех', 'Корица'], base: ['Ваниль', 'Мокко', 'Карамель'] },
    longevityHours: 8, sillage: 3, accords: ['кофейный', 'пряный', 'гурманский'],
    desc: 'Чашка крепкого турецкого кофе с кардамоном — аромат, от которого действительно кружится голова.',
    accent: '#5C3A24',
  },
  {
    slug: 'kilian-rolling-in-love', brand: 'Kilian', name: 'Rolling in Love',
    price: 27500, volume: 50, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Семена амбретты', 'Миндальное молоко'], heart: ['Ирис', 'Фрезия'], base: ['Бобы тонка', 'Ваниль', 'Тубероза'] },
    longevityHours: 6, sillage: 2, accords: ['пудровый', 'сладкий', 'мускусный'],
    desc: 'Миндальное молоко и ирис — нежный аромат-объятие, который хочется вдыхать с чужой кожи.',
    accent: '#B33A4A',
  },
  {
    slug: 'kilian-moonlight-in-heaven', brand: 'Kilian', name: 'Moonlight in Heaven',
    price: 26900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Лимон', 'Грейпфрут', 'Розовый перец'], heart: ['Кокос', 'Жасмин'], base: ['Рис басмати', 'Ветивер', 'Бобы тонка'] },
    longevityHours: 7, sillage: 3, accords: ['цитрусовый', 'фруктовый', 'свежий'],
    desc: 'Грейпфрут, кокос и рис басмати — лёгкий тропический Kilian на каждый день, когда хочется лета.',
    accent: '#7FB4D9',
  },
  {
    slug: 'kilian-vodka-on-the-rocks', brand: 'Kilian', name: 'Vodka on the Rocks',
    price: 28500, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Альдегиды', 'Кориандр'], heart: ['Ревень', 'Кардамон'], base: ['Амброксан', 'Сандал', 'Мускус'] },
    longevityHours: 7, sillage: 3, accords: ['свежий', 'пряный', 'древесный'],
    desc: 'Ледяная рюмка с ревенём и специями: начинался как эксклюзив для Москвы, стал мировым бестселлером дома.',
    accent: '#A8C8DC',
  },
  {
    slug: 'kilian-apple-brandy-on-the-rocks', brand: 'Kilian', name: 'Apple Brandy on the Rocks',
    price: 30900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Яблоко', 'Коньяк'], heart: ['Корица', 'Ром'], base: ['Дубовая бочка', 'Ваниль', 'Амбра'] },
    longevityHours: 8, sillage: 4, accords: ['фруктовый', 'сладкий', 'пряный'],
    desc: 'Яблочный бренди из дубовой бочки — согревающий бар-аромат для тех, кому Angels’ Share показался слишком сладким.',
    accent: '#C08A3E',
  },
  {
    slug: 'kilian-voulez-vous-coucher-avec-moi', brand: 'Kilian', name: 'Voulez-Vous Coucher Avec Moi',
    price: 31900, volume: 50, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Нероли'], heart: ['Тубероза', 'Иланг-иланг', 'Болгарская роза'], base: ['Ваниль', 'Сандал', 'Кедр'] },
    longevityHours: 8, sillage: 4, accords: ['цветочный', 'восточный', 'сладкий'],
    desc: 'Тубероза и иланг-иланг на ванили — откровенный вечерний аромат, название которого говорит само за себя.',
    accent: '#8C7A3E',
  },
  {
    slug: 'kilian-bad-boys-are-no-good', brand: 'Kilian', name: 'Bad Boys Are No Good But Good Boys Are No Fun',
    price: 26500, volume: 50, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Кола', 'Лайм'], heart: ['Корица', 'Яблоко', 'Мускатный орех'], base: ['Кедр', 'Амбровое дерево'] },
    longevityHours: 7, sillage: 3, accords: ['сладкий', 'пряный', 'древесный'],
    desc: 'Шипучая кола с лаймом и корицей — дерзкий и узнаваемый аромат для плохих парней с хорошим вкусом.',
    accent: '#7A4A2E',
  },
  {
    slug: 'kilian-roses-on-ice', brand: 'Kilian', name: 'Roses on Ice',
    price: 29500, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Огурец', 'Можжевельник', 'Лайм'], heart: ['Роза сентифолия'], base: ['Мускус', 'Сандал', 'Амброксан'] },
    longevityHours: 6, sillage: 2, accords: ['свежий', 'цветочный', 'зелёный'],
    desc: 'Джин со льдом и лепестками розы: самая свежая роза в нише — идеальна на жару и офис.',
    accent: '#D9909E',
  },
  {
    slug: 'kilian-sacred-wood', brand: 'Kilian', name: 'Sacred Wood',
    price: 33900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Семена моркови', 'Розовый перец'], heart: ['Майсурский сандал', 'Молоко'], base: ['Кедр', 'Ладан', 'Мирра'] },
    longevityHours: 9, sillage: 3, accords: ['древесный', 'восточный', 'дымный'],
    desc: 'Кремовый майсурский сандал с ладаном — медитативная роскошь для ценителей, эталон древесной ниши.',
    accent: '#A8865C',
  },
  {
    slug: 'kilian-smoking-hot', brand: 'Kilian', name: 'Smoking Hot',
    price: 32900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: ['новинка'],
    notes: { top: ['Яблоко', 'Дым', 'Корица'], heart: ['Табак', 'Ваниль'], base: ['Бурбонская ваниль', 'Лакрица'] },
    longevityHours: 10, sillage: 4, accords: ['табачный', 'дымный', 'сладкий'],
    desc: 'Фотореалистичный яблочный кальян: карамельный дым и табак, которые держатся на коже больше десяти часов.',
    accent: '#A03A2E',
  },

  /* ─── MEMO PARIS ─── */
  {
    slug: 'memo-irish-leather', brand: 'Memo Paris', name: 'Irish Leather',
    price: 27900, volume: 75, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Можжевельник', 'Мате'], heart: ['Цветок ириса', 'Зелёные ноты'], base: ['Кожа', 'Бобы тонка', 'Амбра'] },
    longevityHours: 9, sillage: 3, accords: ['кожаный', 'зелёный', 'свежий'],
    desc: 'Утро в ирландской конюшне: свежескошенная трава, ветер и кожаное седло — самая знаменитая кожа Memo.',
    accent: '#3E6B4A',
  },
  {
    slug: 'memo-french-leather', brand: 'Memo Paris', name: 'French Leather',
    price: 28500, volume: 75, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Лайм', 'Бергамот'], heart: ['Роза', 'Ирис'], base: ['Кожа', 'Стиракс', 'Мускус'] },
    longevityHours: 8, sillage: 3, accords: ['кожаный', 'цветочный', 'мускусный'],
    desc: 'Элегантная парижская кожа, смягчённая розой и лаймом, — строгость без грубости, шик без усилий.',
    accent: '#8C6E5A',
  },
  {
    slug: 'memo-russian-leather', brand: 'Memo Paris', name: 'Russian Leather',
    price: 26900, volume: 75, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Мята', 'Розмарин', 'Базилик'], heart: ['Сибирская сосна', 'Кипарис', 'Лаванда'], base: ['Кожа', 'Пачули', 'Бобы тонка'] },
    longevityHours: 8, sillage: 3, accords: ['кожаный', 'зелёный', 'фужерный'],
    desc: 'Замёрзший хвойный лес и выделанная кожа — суровый зимний аромат с русским характером.',
    accent: '#2E4A3E',
  },
  {
    slug: 'memo-marfa', brand: 'Memo Paris', name: 'Marfa',
    price: 29900, volume: 75, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Персик', 'Мандарин'], heart: ['Тубероза', 'Иланг-иланг', 'Флёрдоранж'], base: ['Ваниль', 'Сандал', 'Мускус'] },
    longevityHours: 9, sillage: 4, accords: ['цветочный', 'сладкий', 'ваниль'],
    desc: 'Солнечная тубероза техасской пустыни: сливочная, тёплая и магнетическая — от неё оборачиваются.',
    accent: '#E0C08A',
  },
  {
    slug: 'memo-kedu', brand: 'Memo Paris', name: 'Kedu',
    price: 24900, volume: 75, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Мандарин', 'Грейпфрут', 'Нероли'], heart: ['Мате', 'Фрезия', 'Пион'], base: ['Кунжут', 'Мох', 'Белый мускус'] },
    longevityHours: 6, sillage: 2, accords: ['цитрусовый', 'свежий', 'зелёный'],
    desc: 'Сочные цитрусы с необычной ноткой кунжута — деликатный дневной аромат, которого нет ни у кого из знакомых.',
    accent: '#E0B84A',
  },
  {
    slug: 'memo-tamarindo', brand: 'Memo Paris', name: 'Tamarindo',
    price: 31900, volume: 75, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Ананас', 'Апельсин', 'Бергамот'], heart: ['Жасмин самбак', 'Персик'], base: ['Ваниль', 'Бензоин', 'Пачули'] },
    longevityHours: 9, sillage: 4, accords: ['фруктовый', 'сладкий', 'восточный'],
    desc: 'Пряная пина-колада на побережье Коста-Рики: сливочный ананас и ваниль для дорогого отпускного настроения.',
    accent: '#D9973E',
  },

  /* ─── PENHALIGON'S ─── */
  {
    slug: 'penhaligons-halfeti', brand: "Penhaligon's", name: 'Halfeti',
    price: 27900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Бергамот', 'Грейпфрут', 'Шафран'], heart: ['Роза', 'Жасмин', 'Мускатный орех'], base: ['Уд', 'Кожа', 'Амбра'] },
    longevityHours: 10, sillage: 4, accords: ['восточный', 'уд', 'кожаный'],
    desc: 'Чёрная турецкая роза в шафране и уде — главный бестселлер Penhaligon’s и один из самых комплиментарных ароматов ниши.',
    accent: '#7A1F2E',
  },
  {
    slug: 'penhaligons-the-tragedy-of-lord-george', brand: "Penhaligon's", name: 'The Tragedy of Lord George',
    price: 25900, volume: 75, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Бренди'], heart: ['Шалфей', 'Лаванда'], base: ['Бобы тонка', 'Амбра', 'Древесные ноты'] },
    longevityHours: 9, sillage: 4, accords: ['амбра', 'фужерный', 'сладкий'],
    desc: 'Бренди и амбра британского аристократа: солидный, тёплый и безупречно воспитанный аромат-смокинг.',
    accent: '#9C6B2E',
  },
  {
    slug: 'penhaligons-the-coveted-duchess-rose', brand: "Penhaligon's", name: 'The Coveted Duchess Rose',
    price: 23900, volume: 75, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Мандарин'], heart: ['Роза', 'Пион'], base: ['Мускус', 'Древесные ноты'] },
    longevityHours: 6, sillage: 2, accords: ['цветочный', 'пудровый', 'мускусный'],
    desc: 'Утренняя английская роза с мандарином — светлый и аккуратный аромат настоящей герцогини.',
    accent: '#E09CB0',
  },
  {
    slug: 'penhaligons-terrible-teddy', brand: "Penhaligon's", name: 'Terrible Teddy',
    price: 24900, volume: 75, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Ладан', 'Розовый перец'], heart: ['Кожа', 'Лабданум'], base: ['Амброксан', 'Амбра'] },
    longevityHours: 8, sillage: 3, accords: ['кожаный', 'дымный', 'пряный'],
    desc: 'Перечный ладан и тёмная кожа — загадочный вечерний аромат для мужчины с репутацией.',
    accent: '#4A4A52',
  },
  {
    slug: 'penhaligons-changing-constance', brand: "Penhaligon's", name: 'Changing Constance',
    price: 22900, volume: 75, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Кардамон', 'Розовый перец'], heart: ['Карамель', 'Морская соль'], base: ['Ваниль', 'Табак', 'Кашмеран'] },
    longevityHours: 8, sillage: 3, accords: ['гурманский', 'ваниль', 'табачный'],
    desc: 'Солёная карамель на ванили и табаке — уютная гурманика уровня люкс, в которую влюбляются с первого вдоха.',
    accent: '#C89050',
  },
  {
    slug: 'penhaligons-luna', brand: "Penhaligon's", name: 'Luna',
    price: 18900, volume: 100, concentration: 'Eau de Toilette', gender: 'у', tags: [],
    notes: { top: ['Лимон', 'Бергамот', 'Можжевельник'], heart: ['Роза', 'Жасмин'], base: ['Пихта', 'Амбра', 'Мускус'] },
    longevityHours: 6, sillage: 2, accords: ['цитрусовый', 'цветочный', 'свежий'],
    desc: 'Лунный свет во флаконе: прохладные цитрусы и роза — чистый, минималистичный и дорогой на слух аромат.',
    accent: '#B0C4D9',
  },
  {
    slug: 'penhaligons-empressa', brand: "Penhaligon's", name: 'Empressa',
    price: 21900, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Красный апельсин', 'Персик', 'Бергамот'], heart: ['Роза', 'Нероли', 'Кассис'], base: ['Ваниль', 'Пачули', 'Мускус'] },
    longevityHours: 8, sillage: 3, accords: ['фруктовый', 'цветочный', 'сладкий'],
    desc: 'Сочный красный апельсин и роза в карамели — женственная классика, элегантная альтернатива люксовым бестселлерам.',
    accent: '#E08A6B',
  },
  {
    slug: 'penhaligons-endymion', brand: "Penhaligon's", name: 'Endymion',
    price: 18500, volume: 100, concentration: 'Eau de Cologne', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Лаванда', 'Шалфей'], heart: ['Кофе', 'Герань', 'Мускатный орех'], base: ['Сандал', 'Мускус', 'Ветивер'] },
    longevityHours: 7, sillage: 3, accords: ['фужерный', 'кофейный', 'пряный'],
    desc: 'Лаванда с кофе и сандалом — джентльменская классика 2003 года, которая до сих пор собирает комплименты.',
    accent: '#3E5A7A',
  },

  /* ─── SERGE LUTENS ─── */
  {
    slug: 'serge-lutens-chergui', brand: 'Serge Lutens', name: 'Chergui',
    price: 16900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Табачный лист', 'Сено'], heart: ['Мёд', 'Ирис', 'Роза'], base: ['Амбра', 'Ладан', 'Мускус'] },
    longevityHours: 9, sillage: 4, accords: ['табачный', 'медовый', 'восточный'],
    desc: 'Горячий ветер пустыни: мёд, сено и табак — легендарный восточный аромат, который любят все.',
    accent: '#B5813E',
  },
  {
    slug: 'serge-lutens-ambre-sultan', brand: 'Serge Lutens', name: 'Ambre Sultan',
    price: 16500, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Кориандр', 'Лавровый лист', 'Орегано'], heart: ['Амбра', 'Смолы'], base: ['Ваниль', 'Бензоин', 'Сандал'] },
    longevityHours: 10, sillage: 4, accords: ['амбра', 'восточный', 'пряный'],
    desc: 'Эталонная амбра с пряными травами — аромат-легенда 1993 года, по которому меряют все остальные амбры.',
    accent: '#C4923E',
  },
  {
    slug: 'serge-lutens-la-fille-de-berlin', brand: 'Serge Lutens', name: 'La Fille de Berlin',
    price: 15900, volume: 50, concentration: 'Eau de Parfum', gender: 'ж', tags: ['хит'],
    notes: { top: ['Роза', 'Герань'], heart: ['Пальмароза', 'Перец'], base: ['Мёд', 'Мох', 'Пачули'] },
    longevityHours: 8, sillage: 3, accords: ['цветочный', 'пряный', 'медовый'],
    desc: 'Бархатная тёмно-красная роза с перцем — характерная, драматичная и самая продаваемая роза Lutens.',
    accent: '#A32638',
  },
  {
    slug: 'serge-lutens-feminite-du-bois', brand: 'Serge Lutens', name: 'Féminité du Bois',
    price: 17900, volume: 50, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Слива', 'Персик', 'Корица'], heart: ['Фиалка', 'Роза', 'Имбирь'], base: ['Кедр', 'Сандал', 'Мускус'] },
    longevityHours: 8, sillage: 3, accords: ['древесный', 'фруктовый', 'пудровый'],
    desc: 'Слива на тёплом кедре — признанный шедевр парфюмерии, перевернувший представление о женских древесных ароматах.',
    accent: '#7A4A6B',
  },
  {
    slug: 'serge-lutens-un-bois-vanille', brand: 'Serge Lutens', name: 'Un Bois Vanille',
    price: 15500, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Лакрица', 'Горький миндаль'], heart: ['Кокосовое молоко', 'Пчелиный воск'], base: ['Ваниль', 'Сандал', 'Бензоин'] },
    longevityHours: 9, sillage: 3, accords: ['ваниль', 'гурманский', 'древесный'],
    desc: 'Копчёная ваниль на сандале с лакрицей — умная ваниль для взрослых, без приторности и детсадовской сладости.',
    accent: '#D9B98C',
  },
  {
    slug: 'serge-lutens-fleurs-doranger', brand: 'Serge Lutens', name: "Fleurs d'Oranger",
    price: 18900, volume: 50, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Цветок апельсина', 'Цитрусы'], heart: ['Тубероза', 'Жасмин', 'Белая роза'], base: ['Мускус', 'Тмин', 'Гибискус'] },
    longevityHours: 8, sillage: 4, accords: ['цветочный', 'восточный', 'мускусный'],
    desc: 'Медовый флёрдоранж во всей красе — чувственный южный полдень, культовые белые цветы от Lutens.',
    accent: '#E5C065',
  },

  /* ─── DIPTYQUE ─── */
  {
    slug: 'diptyque-philosykos', brand: 'Diptyque', name: 'Philosykos',
    price: 18500, volume: 75, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Лист инжира', 'Инжир'], heart: ['Кокос', 'Зелёные ноты'], base: ['Фиговое дерево', 'Кедр'] },
    longevityHours: 7, sillage: 3, accords: ['зелёный', 'древесный', 'фруктовый'],
    desc: 'Целое фиговое дерево во флаконе: листья, плоды и молочная кора — эталон инжира, который копируют все.',
    accent: '#6B8C4A',
  },
  {
    slug: 'diptyque-tam-dao', brand: 'Diptyque', name: 'Tam Dao',
    price: 19500, volume: 75, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Лайм', 'Кориандр'], heart: ['Сандал', 'Кедр'], base: ['Амбровое дерево', 'Мускус', 'Ваниль'] },
    longevityHours: 7, sillage: 2, accords: ['древесный', 'пряный', 'мускусный'],
    desc: 'Тёплый сливочный сандал вьетнамских лесов — спокойный, медитативный аромат-кашемир на каждый день.',
    accent: '#B08D5C',
  },
  {
    slug: 'diptyque-do-son', brand: 'Diptyque', name: 'Do Son',
    price: 19900, volume: 75, concentration: 'Eau de Parfum', gender: 'ж', tags: ['хит'],
    notes: { top: ['Листья апельсина', 'Розовый перец'], heart: ['Тубероза', 'Жасмин'], base: ['Мускус', 'Бензоин'] },
    longevityHours: 8, sillage: 4, accords: ['цветочный', 'свежий', 'мускусный'],
    desc: 'Тубероза на морском бризе — самый продаваемый цветочный Diptyque: свежий, чистый и невероятно женственный.',
    accent: '#E8B4C0',
  },
  {
    slug: 'diptyque-eau-rose', brand: 'Diptyque', name: 'Eau Rose',
    price: 15900, volume: 100, concentration: 'Eau de Toilette', gender: 'ж', tags: [],
    notes: { top: ['Личи', 'Бергамот'], heart: ['Роза сентифолия', 'Дамасская роза'], base: ['Белый мускус', 'Кедр'] },
    longevityHours: 6, sillage: 2, accords: ['цветочный', 'свежий', 'фруктовый'],
    desc: 'Две натуральные розы с личи — лёгкая, живая роза без пудры и «бабушкиности», идеальна на весну.',
    accent: '#DC98A8',
  },
  {
    slug: 'diptyque-orpheon', brand: 'Diptyque', name: 'Orphéon',
    price: 21500, volume: 75, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Ягоды можжевельника', 'Бергамот'], heart: ['Жасмин', 'Ирис'], base: ['Кедр', 'Бобы тонка', 'Пудровые ноты'] },
    longevityHours: 8, sillage: 3, accords: ['древесный', 'пудровый', 'фужерный'],
    desc: 'Парижский джаз-клуб 60-х: джин, жасмин и пудровый кедр — самый стильный унисекс Diptyque последних лет.',
    accent: '#2E3A52',
  },
  {
    slug: 'diptyque-lombre-dans-leau', brand: 'Diptyque', name: "L'Ombre dans l'Eau",
    price: 18500, volume: 75, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Листья чёрной смородины', 'Петигрейн'], heart: ['Болгарская роза', 'Ягоды смородины'], base: ['Зелёные ноты', 'Мускус'] },
    longevityHours: 7, sillage: 3, accords: ['зелёный', 'цветочный', 'фруктовый'],
    desc: 'Сад после летнего дождя: терпкие листья смородины и роза — зелёная классика Diptyque с 1983 года.',
    accent: '#4A7A5A',
  },
  {
    slug: 'diptyque-fleur-de-peau', brand: 'Diptyque', name: 'Fleur de Peau',
    price: 20500, volume: 75, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Альдегиды', 'Розовый перец', 'Бергамот'], heart: ['Ирис', 'Турецкая роза'], base: ['Мускус', 'Амбретта', 'Сандал'] },
    longevityHours: 8, sillage: 3, accords: ['мускусный', 'пудровый', 'цветочный'],
    desc: 'Запах чистой тёплой кожи: мускус и ирис — обладатель премии Fifi, «второй кожей» ложится на тело.',
    accent: '#D9BCA8',
  },
  {
    slug: 'diptyque-eau-duelle', brand: 'Diptyque', name: 'Eau Duelle',
    price: 18900, volume: 75, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Кардамон', 'Розовый перец', 'Можжевельник'], heart: ['Чёрный чай', 'Шафран'], base: ['Бурбонская ваниль', 'Амбра', 'Мускус'] },
    longevityHours: 8, sillage: 3, accords: ['ваниль', 'пряный', 'восточный'],
    desc: 'Сухая пряная ваниль с чёрным чаем — умная ваниль-унисекс без сахара, для тех, кто не любит гурманику.',
    accent: '#C9A05E',
  },
];
