import type { RawProduct } from '../products';

/* ─── СЕГМЕНТ: НИША ПРЕМИУМ — Tom Ford, Creed, MFK, Byredo, Le Labo ─── */

export const SEG_NICHE_TOP: RawProduct[] = [
  /* ── Tom Ford ── */
  {
    slug: 'tf-noir-de-noir', brand: 'Tom Ford', name: 'Noir de Noir',
    price: 34900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Шафран', 'Роза'], heart: ['Чёрная роза', 'Трюфель'], base: ['Пачули', 'Ваниль', 'Уд'] },
    longevityHours: 9, sillage: 4, accords: ['цветочный', 'восточный', 'уд'],
    desc: 'Чёрная роза с трюфелем и ванилью — тёмный бархатный вечерний аромат для тех, кто носит только чёрное.',
    accent: '#5C1E2E',
  },
  {
    slug: 'tf-tuscan-leather', brand: 'Tom Ford', name: 'Tuscan Leather',
    price: 35900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Малина', 'Шафран', 'Тимьян'], heart: ['Жасмин', 'Олибанум'], base: ['Кожа', 'Замша', 'Амбра'] },
    longevityHours: 10, sillage: 4, accords: ['кожаный', 'фруктовый', 'дымный'],
    desc: 'Малина на выделанной коже — легенда Private Blend, с которой начался культ дорогих кожаных ароматов.',
    accent: '#8B3A2E',
  },
  {
    slug: 'tf-neroli-portofino', brand: 'Tom Ford', name: 'Neroli Portofino',
    price: 29900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Нероли', 'Бергамот', 'Лимон'], heart: ['Апельсиновый цвет', 'Жасмин', 'Розмарин'], base: ['Амбра', 'Мускус'] },
    longevityHours: 6, sillage: 3, accords: ['цитрусовый', 'свежий'],
    desc: 'Итальянская Ривьера во флаконе: искрящийся нероли и цитрусы — эталон дорогой летней свежести.',
    accent: '#2E86AB',
  },
  {
    slug: 'tf-soleil-blanc', brand: 'Tom Ford', name: 'Soleil Blanc',
    price: 33900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Фисташка', 'Кардамон', 'Бергамот'], heart: ['Тубероза', 'Иланг-иланг', 'Жасмин'], base: ['Кокос', 'Амбра', 'Бобы тонка'] },
    longevityHours: 8, sillage: 3, accords: ['сладкий', 'цветочный', 'амбра'],
    desc: 'Запах разогретой солнцем кожи на частном пляже: фисташка, кокос и белые цветы — роскошь отпуска круглый год.',
    accent: '#E8CFA0',
  },
  {
    slug: 'tf-cafe-rose', brand: 'Tom Ford', name: 'Café Rose',
    price: 19900, volume: 50, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Турецкая роза', 'Кофе'], heart: ['Болгарская роза', 'Кардамон', 'Пачули'], base: ['Ладан', 'Сандал'] },
    longevityHours: 8, sillage: 3, accords: ['цветочный', 'кофейный', 'пряный'],
    desc: 'Роза, присыпанная свежемолотым кофе, — небанальный цветочный аромат для тех, кому классические розы скучны.',
    accent: '#7E2E45',
  },
  {
    slug: 'tf-vanille-fatale', brand: 'Tom Ford', name: 'Vanille Fatale',
    price: 21500, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: ['новинка'],
    notes: { top: ['Шафран', 'Кориандр'], heart: ['Кофе', 'Франжипани', 'Ячмень'], base: ['Мадагаскарская ваниль', 'Табак', 'Замша'] },
    longevityHours: 9, sillage: 4, accords: ['ваниль', 'гурманский', 'древесный'],
    desc: 'Ваниль для взрослых: тёмная, с кофе, табаком и замшей — никакой кондитерской приторности.',
    accent: '#C9A15A',
  },
  {
    slug: 'tf-white-suede', brand: 'Tom Ford', name: 'White Suede',
    price: 28900, volume: 50, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Чай', 'Тимьян'], heart: ['Ландыш', 'Шафран', 'Роза'], base: ['Замша', 'Мускус', 'Сандал'] },
    longevityHours: 7, sillage: 2, accords: ['мускусный', 'кожаный', 'пудровый'],
    desc: 'Белая замша и чистый мускус — аромат кашемирового свитера, уютный и дорогой «второй кожей».',
    accent: '#D8CBBB',
  },
  {
    slug: 'tf-rose-prick', brand: 'Tom Ford', name: 'Rose Prick',
    price: 32900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Сычуаньский перец', 'Куркума'], heart: ['Майская роза', 'Болгарская роза', 'Турецкая роза'], base: ['Пачули', 'Бобы тонка'] },
    longevityHours: 8, sillage: 3, accords: ['цветочный', 'пряный', 'шипровый'],
    desc: 'Три розы с шипами: перец и куркума делают букет колючим и дерзким — роза с характером.',
    accent: '#D96C8A',
  },
  {
    slug: 'tf-ebene-fume', brand: 'Tom Ford', name: 'Ébène Fumé',
    price: 34900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Ладан', 'Пало санто', 'Чёрный перец'], heart: ['Кожа', 'Лабданум', 'Папирус'], base: ['Эбеновое дерево', 'Гваяк', 'Смолы'] },
    longevityHours: 10, sillage: 4, accords: ['дымный', 'древесный', 'восточный'],
    desc: 'Дым пало санто и копчёное эбеновое дерево — медитативный и мистический, для ценителей тёмных ароматов.',
    accent: '#3A3335',
  },
  {
    slug: 'tf-vanilla-sex', brand: 'Tom Ford', name: 'Vanilla Sex',
    price: 36900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: ['новинка'],
    notes: { top: ['Ваниль', 'Корень ириса'], heart: ['Жасмин', 'Сандал'], base: ['Ванильная настойка', 'Мускус', 'Амбра'] },
    longevityHours: 9, sillage: 3, accords: ['ваниль', 'гурманский', 'мускусный'],
    desc: 'Самая обсуждаемая ваниль последних лет: кремовая, чувственная, на грани приличия — как и её название.',
    accent: '#EAD3B5',
  },
  {
    slug: 'tf-noir-extreme', brand: 'Tom Ford', name: 'Noir Extreme',
    price: 18900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Кардамон', 'Шафран', 'Манго'], heart: ['Кулфи', 'Роза', 'Жасмин'], base: ['Ваниль', 'Бобы тонка', 'Сандал'] },
    longevityHours: 9, sillage: 4, accords: ['восточный', 'сладкий', 'пряный'],
    desc: 'Пряный десерт кулфи с ванилью и сандалом — вечерняя классика Tom Ford, собирающая комплименты на свиданиях.',
    accent: '#3B3547',
  },
  {
    slug: 'tf-grey-vetiver', brand: 'Tom Ford', name: 'Grey Vetiver',
    price: 16900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Грейпфрут', 'Апельсиновый цвет', 'Шалфей'], heart: ['Ирис', 'Мускатный орех', 'Пименто'], base: ['Ветивер', 'Дубовый мох', 'Амбровое дерево'] },
    longevityHours: 8, sillage: 3, accords: ['древесный', 'свежий', 'фужерный'],
    desc: 'Безупречный ветивер в сером костюме: строгий офисный аромат, который считывается как «человек при деньгах».',
    accent: '#7C8577',
  },

  /* ── Creed ── */
  {
    slug: 'creed-aventus-for-her', brand: 'Creed', name: 'Aventus for Her',
    price: 33900, volume: 75, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Зелёное яблоко', 'Бергамот', 'Розовый перец'], heart: ['Роза', 'Сандал', 'Стиракс'], base: ['Персик', 'Чёрная смородина', 'Амбра'] },
    longevityHours: 8, sillage: 3, accords: ['фруктовый', 'шипровый', 'цветочный'],
    desc: 'Женская версия легендарного Aventus: сочное яблоко, роза и персик — аромат уверенной в себе победительницы.',
    accent: '#C48EA0',
  },
  {
    slug: 'creed-millesime-imperial', brand: 'Creed', name: 'Millésime Impérial',
    price: 34900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Арбуз', 'Морская соль', 'Бергамот'], heart: ['Лимон', 'Ирис', 'Мандарин'], base: ['Мускус', 'Амбергрис', 'Древесные ноты'] },
    longevityHours: 7, sillage: 3, accords: ['цитрусовый', 'акватический', 'свежий'],
    desc: 'Морская соль и цитрусы Сицилии в золотом флаконе — аромат яхты, белой рубашки и лёгких денег.',
    accent: '#D4AF37',
  },
  {
    slug: 'creed-royal-oud', brand: 'Creed', name: 'Royal Oud',
    price: 33900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Лимон', 'Розовый перец', 'Бергамот'], heart: ['Гальбанум', 'Кедр', 'Ангелика'], base: ['Уд', 'Сандал', 'Мускус'] },
    longevityHours: 9, sillage: 3, accords: ['уд', 'древесный', 'пряный'],
    desc: 'Уд по-европейски: полированное дерево дворцовых залов вместо тяжёлого востока — интеллигентная роскошь.',
    accent: '#6B4F35',
  },
  {
    slug: 'creed-virgin-island-water', brand: 'Creed', name: 'Virgin Island Water',
    price: 32900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Кокос', 'Лайм', 'Мандарин'], heart: ['Имбирь', 'Иланг-иланг', 'Жасмин'], base: ['Белый ром', 'Сахарный тростник', 'Мускус'] },
    longevityHours: 7, sillage: 3, accords: ['цитрусовый', 'сладкий', 'акватический'],
    desc: 'Кокос, лайм и белый ром — пина-колада на борту яхты у Карибских островов; лучший отпускной аромат в истории.',
    accent: '#4FC3D9',
  },
  {
    slug: 'creed-viking', brand: 'Creed', name: 'Viking',
    price: 31900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Лимон', 'Розовый перец'], heart: ['Роза', 'Перечная мята', 'Ландыш'], base: ['Ветивер', 'Сандал', 'Пачули'] },
    longevityHours: 8, sillage: 3, accords: ['пряный', 'фужерный', 'древесный'],
    desc: 'Перечно-древесный шторм в алом флаконе — мужественный Creed для тех, кому Aventus слишком популярен.',
    accent: '#8E2F3C',
  },
  {
    slug: 'creed-himalaya', brand: 'Creed', name: 'Himalaya',
    price: 29900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Грейпфрут', 'Лимон', 'Бергамот'], heart: ['Сандал', 'Специи'], base: ['Мускус', 'Амбра', 'Кедр'] },
    longevityHours: 7, sillage: 3, accords: ['свежий', 'древесный', 'амбра'],
    desc: 'Ледяная свежесть горного воздуха и тёплый сандал — самый чистый и универсальный мужской Creed.',
    accent: '#9FB4C7',
  },
  {
    slug: 'creed-original-santal', brand: 'Creed', name: 'Original Santal',
    price: 33500, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: ['новинка'],
    notes: { top: ['Сандал', 'Можжевельник', 'Корица'], heart: ['Лаванда', 'Имбирь', 'Розмарин'], base: ['Бобы тонка', 'Ваниль'] },
    longevityHours: 9, sillage: 4, accords: ['древесный', 'пряный', 'сладкий'],
    desc: 'Королевский индийский сандал с корицей и ванилью — тёплая классика Creed в обновлённом издании.',
    accent: '#A6763C',
  },
  {
    slug: 'creed-love-in-white', brand: 'Creed', name: 'Love in White',
    price: 30900, volume: 75, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Яблоко', 'Апельсин', 'Абрикос'], heart: ['Магнолия', 'Ирис', 'Жасмин', 'Рис'], base: ['Кедр', 'Мускус'] },
    longevityHours: 7, sillage: 2, accords: ['цветочный', 'пудровый', 'мускусный'],
    desc: 'Аромат первых леди: белые цветы и хрустящее свежее бельё — его носили в Белом доме, теперь может носить и она.',
    accent: '#EDE6DA',
  },

  /* ── Maison Francis Kurkdjian ── */
  {
    slug: 'mfk-oud-satin-mood', brand: 'Maison Francis Kurkdjian', name: 'Oud Satin Mood',
    price: 35900, volume: 70, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Болгарская роза', 'Фиалка'], heart: ['Турецкая роза', 'Дамасская роза'], base: ['Уд', 'Ваниль', 'Амбра', 'Бензоин'] },
    longevityHours: 12, sillage: 5, accords: ['уд', 'сладкий', 'восточный'],
    desc: 'Атласная роза на подушке из уда и ванили — восточная роскошь от создателя Baccarat Rouge, шлейф на всю улицу.',
    accent: '#6E2F5C',
  },
  {
    slug: 'mfk-gentle-fluidity-gold', brand: 'Maison Francis Kurkdjian', name: 'Gentle Fluidity Gold',
    price: 26900, volume: 70, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Можжевельник', 'Мускатный орех'], heart: ['Кориандр', 'Специи'], base: ['Ваниль', 'Мускус', 'Амбровое дерево'] },
    longevityHours: 10, sillage: 4, accords: ['ваниль', 'мускусный', 'пудровый'],
    desc: 'Пудровая ваниль с рахат-лукумом и мускусом — уютный и обволакивающий, младший брат Baccarat Rouge.',
    accent: '#D4A73E',
  },
  {
    slug: 'mfk-gentle-fluidity-silver', brand: 'Maison Francis Kurkdjian', name: 'Gentle Fluidity Silver',
    price: 25900, volume: 70, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Можжевельник', 'Бергамот', 'Мускатный орех'], heart: ['Кориандр', 'Кедр'], base: ['Мускус', 'Амбровое дерево', 'Ваниль'] },
    longevityHours: 8, sillage: 3, accords: ['свежий', 'пряный', 'древесный'],
    desc: 'Те же ноты, что в Gold, но собранные в ледяной джин-тоник с древесиной, — эксперимент Куркджяна для минималистов.',
    accent: '#B9C1C9',
  },
  {
    slug: 'mfk-a-la-rose', brand: 'Maison Francis Kurkdjian', name: 'À la Rose',
    price: 27900, volume: 70, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Бергамот', 'Личи', 'Груша'], heart: ['Дамасская роза', 'Роза сентифолия', 'Фиалка'], base: ['Мускус', 'Кедр'] },
    longevityHours: 7, sillage: 3, accords: ['цветочный', 'фруктовый', 'мускусный'],
    desc: 'Двести роз в одном флаконе: свежий утренний букет без тяжести — признание в любви от Франсиса Куркджяна.',
    accent: '#F2B8C6',
  },
  {
    slug: 'mfk-aqua-celestia', brand: 'Maison Francis Kurkdjian', name: 'Aqua Celestia',
    price: 21900, volume: 70, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Лайм', 'Мята', 'Чёрная смородина'], heart: ['Мимоза', 'Роза', 'Зелёные ноты'], base: ['Белый мускус', 'Кедр'] },
    longevityHours: 6, sillage: 2, accords: ['свежий', 'акватический', 'зелёный'],
    desc: 'Небо, встречающееся с морем: прохладная мята, лайм и мимоза — невесомая свежесть для жарких дней.',
    accent: '#7FD1E8',
  },
  {
    slug: 'mfk-724', brand: 'Maison Francis Kurkdjian', name: '724',
    price: 24900, volume: 70, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Альдегиды', 'Калабрийский бергамот'], heart: ['Жасмин', 'Чубушник', 'Душистый горошек'], base: ['Белый мускус', 'Сандал'] },
    longevityHours: 8, sillage: 3, accords: ['свежий', 'мускусный', 'цветочный'],
    desc: 'Запах чистой рубашки и большого города 24/7: сияющие альдегиды и белый мускус — идеальный «чистый» аромат.',
    accent: '#C7CED6',
  },
  {
    slug: 'mfk-amyris-femme', brand: 'Maison Francis Kurkdjian', name: 'Amyris Femme',
    price: 22900, volume: 70, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Цветок лимона', 'Калифорнийский апельсин'], heart: ['Амирис', 'Ирис'], base: ['Ветивер', 'Мускус', 'Амбра'] },
    longevityHours: 7, sillage: 2, accords: ['цветочный', 'древесный', 'пудровый'],
    desc: 'Кремовый ирис и древесина амириса — тихая элегантность на каждый день, от офиса до ужина.',
    accent: '#E3C9A8',
  },

  /* ── Byredo ── */
  {
    slug: 'byredo-blanche', brand: 'Byredo', name: 'Blanche',
    price: 22900, volume: 50, concentration: 'Eau de Parfum', gender: 'ж', tags: ['хит'],
    notes: { top: ['Альдегиды', 'Белая роза'], heart: ['Пион', 'Фиалка'], base: ['Мускус', 'Сандал'] },
    longevityHours: 6, sillage: 2, accords: ['мускусный', 'пудровый', 'цветочный'],
    desc: 'Свежие простыни пятизвёздочного отеля: самый знаменитый «чистый» аромат в мире — о нём спрашивают все.',
    accent: '#EDE9E1',
  },
  {
    slug: 'byredo-bibliotheque', brand: 'Byredo', name: 'Bibliothèque',
    price: 26900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Слива', 'Персик'], heart: ['Фиалка', 'Пион'], base: ['Кожа', 'Пачули', 'Ваниль'] },
    longevityHours: 9, sillage: 3, accords: ['фруктовый', 'кожаный', 'ваниль'],
    desc: 'Старая библиотека: кожаные переплёты, ваниль страниц и спелая слива — культовая свеча Byredo, ставшая парфюмом.',
    accent: '#7A4A3A',
  },
  {
    slug: 'byredo-black-saffron', brand: 'Byredo', name: 'Black Saffron',
    price: 23900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Шафран', 'Помело', 'Можжевельник'], heart: ['Чёрная фиалка', 'Кожа', 'Малина'], base: ['Кашмеран', 'Ветивер'] },
    longevityHours: 8, sillage: 3, accords: ['пряный', 'кожаный', 'фруктовый'],
    desc: 'Золотой шафран, чёрная фиалка и замшевая кожа — специи детства основателя Byredo в скандинавской огранке.',
    accent: '#8C4A2F',
  },
  {
    slug: 'byredo-rose-of-no-mans-land', brand: 'Byredo', name: "Rose of No Man's Land",
    price: 24900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Розовый перец', 'Турецкая роза'], heart: ['Малина', 'Роза'], base: ['Папирус', 'Амбра'] },
    longevityHours: 7, sillage: 3, accords: ['цветочный', 'фруктовый', 'амбра'],
    desc: 'Роза с малиной, посвящённая медсёстрам Первой мировой, — нежность со стальным стержнем, бестселлер Byredo.',
    accent: '#E58FA4',
  },
  {
    slug: 'byredo-super-cedar', brand: 'Byredo', name: 'Super Cedar',
    price: 21900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Роза', 'Розовый перец'], heart: ['Виргинский кедр', 'Древесные ноты'], base: ['Гаитянский ветивер', 'Мускус'] },
    longevityHours: 7, sillage: 2, accords: ['древесный', 'мускусный', 'свежий'],
    desc: 'Чистый карандашный кедр с лепестком розы — древесный минимализм, который носится как любимая белая футболка.',
    accent: '#C19A6B',
  },
  {
    slug: 'byredo-pulp', brand: 'Byredo', name: 'Pulp',
    price: 25900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Чёрная смородина', 'Бергамот', 'Кардамон'], heart: ['Инжир', 'Красное яблоко', 'Тиаре'], base: ['Пралине', 'Цветы персика', 'Кедр'] },
    longevityHours: 8, sillage: 4, accords: ['фруктовый', 'сладкий', 'зелёный'],
    desc: 'Взрыв перезрелых фруктов: инжир, смородина и яблоко на грани брожения — самый сочный аромат ниши.',
    accent: '#C4272E',
  },
  {
    slug: 'byredo-la-tulipe', brand: 'Byredo', name: 'La Tulipe',
    price: 22900, volume: 50, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Ревень', 'Цикламен', 'Фрезия'], heart: ['Тюльпан', 'Зелёные ноты'], base: ['Белые древесные ноты', 'Ветивер'] },
    longevityHours: 6, sillage: 2, accords: ['цветочный', 'зелёный', 'свежий'],
    desc: 'Свежесрезанный тюльпан и стебли с каплями росы — сама весна, аккуратно закрытая во флаконе.',
    accent: '#F0A5B4',
  },
  {
    slug: 'byredo-oud-immortel', brand: 'Byredo', name: 'Oud Immortel',
    price: 26900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Лимончелло', 'Ладан', 'Кардамон'], heart: ['Уд', 'Пачули', 'Папирус'], base: ['Дубовый мох', 'Табак'] },
    longevityHours: 9, sillage: 4, accords: ['уд', 'дымный', 'шипровый'],
    desc: 'Уд без тяжести: лимончелло в открытке, дым и табак в подписи — восток глазами Стокгольма.',
    accent: '#5B4632',
  },

  /* ── Le Labo ── */
  {
    slug: 'le-labo-rose-31', brand: 'Le Labo', name: 'Rose 31',
    price: 27900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Роза', 'Кумин', 'Чёрный перец'], heart: ['Гвоздика', 'Мускатный орех', 'Кедр'], base: ['Гваяк', 'Мускус', 'Амбра'] },
    longevityHours: 8, sillage: 3, accords: ['цветочный', 'пряный', 'древесный'],
    desc: 'Роза, которую носят мужчины: специи и дымные породы дерева превращают цветок в характер.',
    accent: '#B76E79',
  },
  {
    slug: 'le-labo-bergamote-22', brand: 'Le Labo', name: 'Bergamote 22',
    price: 26900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Бергамот', 'Лимон', 'Грейпфрут'], heart: ['Апельсиновый цвет', 'Петигрен'], base: ['Ветивер', 'Мускус', 'Амбра'] },
    longevityHours: 7, sillage: 3, accords: ['цитрусовый', 'свежий', 'мускусный'],
    desc: 'Только что надорванная кожура бергамота — самый живой цитрус в нише, свежесть с мускусным послевкусием.',
    accent: '#D9C24A',
  },
  {
    slug: 'le-labo-the-noir-29', brand: 'Le Labo', name: 'Thé Noir 29',
    price: 28900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Инжир', 'Лавровый лист', 'Бергамот'], heart: ['Кедр', 'Ветивер', 'Мускус'], base: ['Табак', 'Сено'] },
    longevityHours: 9, sillage: 3, accords: ['табачный', 'древесный', 'зелёный'],
    desc: 'Чёрный чай в деревянном ящике, инжир и сено — интеллигентный аромат, о котором незнакомцы спрашивают шёпотом.',
    accent: '#4E3B2A',
  },
  {
    slug: 'le-labo-matcha-26', brand: 'Le Labo', name: 'Thé Matcha 26',
    price: 27900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Горький апельсин', 'Инжир'], heart: ['Чай матча', 'Зелёные ноты'], base: ['Ветивер', 'Кедр'] },
    longevityHours: 6, sillage: 2, accords: ['зелёный', 'древесный', 'свежий'],
    desc: 'Кремовый матча-латте с инжиром — тихий скин-сент для тех, кто пускает к себе только близких.',
    accent: '#8FBF6F',
  },
  {
    slug: 'le-labo-patchouli-24', brand: 'Le Labo', name: 'Patchouli 24',
    price: 28900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Пачули', 'Берёза'], heart: ['Стиракс', 'Дымные ноты'], base: ['Ваниль', 'Кожа'] },
    longevityHours: 10, sillage: 4, accords: ['дымный', 'кожаный', 'ваниль'],
    desc: 'Костёр, дёготь и ваниль: самый брутальный Le Labo — кожаная куртка, пропахшая дымом ночного клуба.',
    accent: '#4A3A2C',
  },
  {
    slug: 'le-labo-tonka-25', brand: 'Le Labo', name: 'Tonka 25',
    price: 27900, volume: 50, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Апельсиновый цвет', 'Атласский кедр'], heart: ['Бобы тонка', 'Стиракс'], base: ['Ваниль', 'Мускус'] },
    longevityHours: 9, sillage: 3, accords: ['сладкий', 'пудровый', 'древесный'],
    desc: 'Тёплые бобы тонка и мускус ближе десяти сантиметров к коже — уютный аромат-объятие на осень и зиму.',
    accent: '#B8875B',
  },
];
