import type { RawProduct } from '../products';

/* ─── ДИЗАЙНЕРСКИЕ МУЖСКИЕ/УНИСЕКС БЕСТСЕЛЛЕРЫ ─── */
export const SEG_DESIGNER_M: RawProduct[] = [
  {
    slug: 'versace-eros-parfum', brand: 'Versace', name: 'Eros Parfum',
    price: 12900, volume: 100, concentration: 'Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Мята', 'Лимон', 'Чёрный перец'], heart: ['Зелёное яблоко', 'Герань', 'Шалфей'], base: ['Бобы тонка', 'Амбра', 'Ваниль'] },
    longevityHours: 11, sillage: 4, accords: ['свежий', 'сладкий', 'амбра'],
    desc: 'Самая мощная версия Eros: мята и яблоко на густой амбре, стойкость и шлейф заметно выше классики.',
    accent: '#2E8B84',
  },
  {
    slug: 'versace-dylan-blue', brand: 'Versace', name: 'Pour Homme Dylan Blue',
    price: 10900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Грейпфрут', 'Инжирный лист'], heart: ['Листья фиалки', 'Папирус', 'Чёрный перец'], base: ['Мускус', 'Бобы тонка', 'Шафран'] },
    longevityHours: 8, sillage: 4, accords: ['свежий', 'акватический', 'фужерный'],
    desc: 'Синий Versace на каждый день: акватическая свежесть с перцем и мускусом, которая нравится всем.',
    accent: '#1E3C6E',
  },
  {
    slug: 'versace-pour-homme', brand: 'Versace', name: 'Pour Homme',
    price: 9500, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Лимон', 'Бергамот', 'Нероли'], heart: ['Гиацинт', 'Кедр', 'Герань'], base: ['Мускус', 'Бобы тонка', 'Амбра'] },
    longevityHours: 7, sillage: 3, accords: ['цитрусовый', 'фужерный', 'свежий'],
    desc: 'Средиземноморская классика от Альберто Морильяса: чистый цитрус для офиса, лета и белой рубашки.',
    accent: '#C9D6E2',
  },
  {
    slug: 'dg-the-one-edp', brand: 'Dolce & Gabbana', name: 'The One for Men Eau de Parfum',
    price: 13500, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Грейпфрут', 'Кориандр', 'Базилик'], heart: ['Кардамон', 'Имбирь', 'Апельсиновый цвет'], base: ['Амбра', 'Табак', 'Кедр'] },
    longevityHours: 8, sillage: 3, accords: ['табачный', 'пряный', 'амбра'],
    desc: 'Тёплый табак и амбра в смокинге — эталон вечерней элегантности и один из главных «свиданческих» ароматов.',
    accent: '#4A3A28',
  },
  {
    slug: 'dg-k-edp', brand: 'Dolce & Gabbana', name: 'K Eau de Parfum',
    price: 11900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Кровавый апельсин', 'Можжевельник', 'Кардамон'], heart: ['Лаванда', 'Герань', 'Шалфей'], base: ['Кедр', 'Пачули', 'Ветивер'] },
    longevityHours: 8, sillage: 3, accords: ['древесный', 'пряный', 'свежий'],
    desc: 'Корона на каждый день: пряный цитрус на древесной базе — недооценённый работяга от D&G.',
    accent: '#B08A3E',
  },
  {
    slug: 'dg-light-blue-pour-homme', brand: 'Dolce & Gabbana', name: 'Light Blue Pour Homme',
    price: 10500, volume: 125, concentration: 'Eau de Toilette', gender: 'м', tags: ['хит'],
    notes: { top: ['Грейпфрут', 'Бергамот', 'Мандарин'], heart: ['Розмарин', 'Можжевельник', 'Перец'], base: ['Мускус', 'Ладан', 'Дубовый мох'] },
    longevityHours: 6, sillage: 3, accords: ['цитрусовый', 'свежий', 'акватический'],
    desc: 'Капри во флаконе: грейпфрут и розмарин — летний бестселлер, который узнают с одного пшика.',
    accent: '#7AB8D8',
  },
  {
    slug: 'givenchy-gentleman-society', brand: 'Givenchy', name: 'Gentleman Society',
    price: 13900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: ['новинка'],
    notes: { top: ['Кардамон', 'Шалфей'], heart: ['Нарцисс', 'Ветивер'], base: ['Ваниль', 'Пало санто', 'Кедр'] },
    longevityHours: 9, sillage: 3, accords: ['древесный', 'ваниль', 'цветочный'],
    desc: 'Нарцисс на ванильном дереве — один из лучших дизайнерских релизов последних лет, современный джентльмен.',
    accent: '#3E4A38',
  },
  {
    slug: 'guerlain-lhomme-ideal-edp', brand: 'Guerlain', name: "L'Homme Idéal Eau de Parfum",
    price: 14900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Миндаль', 'Бергамот', 'Лаванда'], heart: ['Вишня', 'Ваниль', 'Ладан'], base: ['Бобы тонка', 'Кожа', 'Сандал'] },
    longevityHours: 9, sillage: 4, accords: ['гурманский', 'сладкий', 'кожаный'],
    desc: 'Вишня в амаретто с кожей — «идеальный мужчина» по версии Guerlain и магнит для комплиментов.',
    accent: '#7A2E38',
  },
  {
    slug: 'guerlain-vetiver', brand: 'Guerlain', name: 'Vetiver',
    price: 12900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Лимон', 'Мандарин'], heart: ['Ветивер', 'Кедр'], base: ['Табачный лист', 'Перец', 'Бобы тонка'] },
    longevityHours: 7, sillage: 2, accords: ['зелёный', 'древесный', 'свежий'],
    desc: 'Эталонный ветивер, на который равняются с 1959 года: свежескошенная трава и земля после дождя.',
    accent: '#5A6E42',
  },
  {
    slug: 'guerlain-habit-rouge-edp', brand: 'Guerlain', name: 'Habit Rouge Eau de Parfum',
    price: 13900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Апельсин', 'Бергамот', 'Лайм'], heart: ['Роза', 'Корица', 'Сандал'], base: ['Ваниль', 'Кожа', 'Амбра'] },
    longevityHours: 9, sillage: 3, accords: ['восточный', 'кожаный', 'ваниль'],
    desc: 'Красный фрак Guerlain: цитрус поверх ванильной кожи — парижская классика верховой езды с 1965 года.',
    accent: '#A82E28',
  },
  {
    slug: 'hermes-h24', brand: 'Hermès', name: 'H24',
    price: 12900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Шалфей мускатный', 'Зелёные ноты'], heart: ['Нарцисс', 'Розовое дерево'], base: ['Скларен', 'Древесные ноты'] },
    longevityHours: 7, sillage: 3, accords: ['зелёный', 'свежий', 'древесный'],
    desc: 'Hermès нового поколения: зелёный, слегка «металлический» и футуристичный — свежесть без единого клише.',
    accent: '#8CB89E',
  },
  {
    slug: 'terre-dhermes-parfum', brand: 'Hermès', name: "Terre d'Hermès Parfum",
    price: 15900, volume: 75, concentration: 'Parfum', gender: 'м', tags: [],
    notes: { top: ['Апельсин', 'Грейпфрут'], heart: ['Кремень', 'Перец'], base: ['Дубовый мох', 'Бензоин', 'Древесные ноты'] },
    longevityHours: 10, sillage: 3, accords: ['древесный', 'цитрусовый', 'шипровый'],
    desc: 'Более глубокая и минеральная версия легенды: апельсин на тёплом камне, стойкость выше классической туалетной.',
    accent: '#B86A28',
  },
  {
    slug: 'chanel-allure-homme-sport', brand: 'Chanel', name: 'Allure Homme Sport',
    price: 15500, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: ['хит'],
    notes: { top: ['Апельсин', 'Мандарин', 'Морские ноты'], heart: ['Перец', 'Нероли', 'Кедр'], base: ['Ваниль', 'Бобы тонка', 'Белый мускус'] },
    longevityHours: 8, sillage: 3, accords: ['цитрусовый', 'свежий', 'ваниль'],
    desc: 'Апельсин на ванильном мускусе — двадцать лет в топе «спортивной элегантности» Chanel.',
    accent: '#C0C8D0',
  },
  {
    slug: 'bleu-de-chanel-parfum', brand: 'Chanel', name: 'Bleu de Chanel Parfum',
    price: 19500, volume: 100, concentration: 'Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Цедра лимона', 'Бергамот', 'Мята'], heart: ['Лаванда', 'Герань', 'Ананас'], base: ['Сандал', 'Кедр', 'Бобы тонка'] },
    longevityHours: 10, sillage: 4, accords: ['древесный', 'свежий', 'амбра'],
    desc: 'Максимальная версия Bleu: глубже, дороже, с кремовым новокаледонским сандалом в базе.',
    accent: '#16283E',
  },
  {
    slug: 'chanel-egoiste-platinum', brand: 'Chanel', name: 'Égoïste Platinum',
    price: 16900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Лаванда', 'Розмарин', 'Нероли'], heart: ['Герань', 'Шалфей', 'Жасмин'], base: ['Дубовый мох', 'Ветивер', 'Сандал'] },
    longevityHours: 7, sillage: 3, accords: ['фужерный', 'свежий', 'зелёный'],
    desc: 'Платиновая классика 90-х: безупречная свежесть «только из душа» в исполнении Chanel.',
    accent: '#B8BEC8',
  },
  {
    slug: 'dior-homme-intense', brand: 'Dior', name: 'Dior Homme Intense',
    price: 16500, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Лаванда'], heart: ['Ирис', 'Амбретта', 'Груша'], base: ['Виргинский кедр', 'Ветивер'] },
    longevityHours: 9, sillage: 4, accords: ['пудровый', 'древесный', 'цветочный'],
    desc: 'Бархатный ирис с грушей — самый элегантный вечерний Dior, современная классика соблазнения.',
    accent: '#6E6478',
  },
  {
    slug: 'dior-fahrenheit', brand: 'Dior', name: 'Fahrenheit',
    price: 15500, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Мандарин', 'Лаванда', 'Боярышник'], heart: ['Фиалковый лист', 'Мускатный орех', 'Кедр'], base: ['Кожа', 'Ветивер', 'Мускус'] },
    longevityHours: 9, sillage: 4, accords: ['кожаный', 'цветочный', 'древесный'],
    desc: 'Легенда 1988 года: фиалка и «бензиновая» кожа — аромат, который не спутать ни с чем на свете.',
    accent: '#C84A18',
  },
  {
    slug: 'ysl-la-nuit-de-lhomme', brand: 'Yves Saint Laurent', name: "La Nuit de L'Homme",
    price: 12900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: ['хит'],
    notes: { top: ['Кардамон', 'Бергамот'], heart: ['Лаванда', 'Кедр'], base: ['Ветивер', 'Кумарин'] },
    longevityHours: 7, sillage: 3, accords: ['пряный', 'сладкий', 'древесный'],
    desc: 'Кардамон в полумраке — культовый аромат свиданий, у которого целые форумы фанатов.',
    accent: '#2A2226',
  },
  {
    slug: 'ysl-y-le-parfum', brand: 'Yves Saint Laurent', name: 'Y Le Parfum',
    price: 14500, volume: 100, concentration: 'Parfum', gender: 'м', tags: [],
    notes: { top: ['Яблоко', 'Грейпфрут', 'Имбирь'], heart: ['Лаванда', 'Шалфей', 'Герань'], base: ['Кедр', 'Бобы тонка', 'Амбра'] },
    longevityHours: 10, sillage: 4, accords: ['фужерный', 'древесный', 'амбра'],
    desc: 'Самая тёмная и стойкая версия Y: свежее яблоко на тёплой смолистой базе — вечер и холода.',
    accent: '#8E9498',
  },
  {
    slug: 'ysl-myslf', brand: 'Yves Saint Laurent', name: 'MYSLF',
    price: 14900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: ['новинка'],
    notes: { top: ['Бергамот', 'Цитрусовая цедра'], heart: ['Апельсиновый цвет', 'Жасмин'], base: ['Амброфикс', 'Пачули'] },
    longevityHours: 8, sillage: 3, accords: ['цветочный', 'свежий', 'мускусный'],
    desc: 'Новое лицо YSL: мужской белый цветок на чистом мускусе — современно, дорого, без сладости.',
    accent: '#3A3A3E',
  },
  {
    slug: 'prada-luna-rossa-carbon', brand: 'Prada', name: 'Luna Rossa Carbon',
    price: 12500, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Лаванда'], heart: ['Металлические ноты', 'Пачули'], base: ['Амброксан', 'Древесные ноты'] },
    longevityHours: 8, sillage: 3, accords: ['фужерный', 'свежий', 'древесный'],
    desc: 'Лаванда и минеральный амброксан: строгий «технологичный» аромат для города и офиса.',
    accent: '#2E2E33',
  },
  {
    slug: 'prada-luna-rossa-ocean', brand: 'Prada', name: 'Luna Rossa Ocean',
    price: 13500, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Морские ноты'], heart: ['Ирис', 'Лаванда'], base: ['Амбра', 'Древесные ноты'] },
    longevityHours: 8, sillage: 3, accords: ['акватический', 'свежий', 'древесный'],
    desc: 'Парусная регата Prada: ирис на морском бризе — свежесть с характером дорогой яхты.',
    accent: '#123A5E',
  },
  {
    slug: 'paco-phantom', brand: 'Rabanne', name: 'Phantom',
    price: 11900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Лимон', 'Лаванда', 'Яблоко'], heart: ['Земляные ноты', 'Пачули'], base: ['Ваниль', 'Ветивер'] },
    longevityHours: 9, sillage: 4, accords: ['фужерный', 'сладкий', 'ваниль'],
    desc: 'Робот-соблазнитель: лимонная лаванда на кремовой ванили — молодёжный хит Rabanne.',
    accent: '#8A94A6',
  },
  {
    slug: 'paco-one-million-elixir', brand: 'Rabanne', name: '1 Million Elixir',
    price: 14900, volume: 100, concentration: 'Parfum Intense', gender: 'м', tags: [],
    notes: { top: ['Давана', 'Яблоко'], heart: ['Дамасская роза', 'Османтус', 'Кедр'], base: ['Ваниль', 'Бобы тонка', 'Пачули'] },
    longevityHours: 12, sillage: 5, accords: ['сладкий', 'фруктовый', 'ваниль'],
    desc: 'Самый мощный «миллион»: вишнёво-ромовая давана на густой ванили, шлейф на весь вечер.',
    accent: '#7A5A18',
  },
  {
    slug: 'paco-invictus-victory', brand: 'Rabanne', name: 'Invictus Victory',
    price: 12500, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Лимон', 'Чёрный перец'], heart: ['Лаванда', 'Ладан'], base: ['Бобы тонка', 'Амбра', 'Ваниль'] },
    longevityHours: 10, sillage: 4, accords: ['сладкий', 'пряный', 'амбра'],
    desc: 'Золотой кубок с ванилью: сладкая победная версия Invictus для вечера и холодов.',
    accent: '#C0A85A',
  },
  {
    slug: 'jpg-le-male', brand: 'Jean Paul Gaultier', name: 'Le Male',
    price: 10900, volume: 125, concentration: 'Eau de Toilette', gender: 'м', tags: ['хит'],
    notes: { top: ['Лаванда', 'Мята', 'Бергамот'], heart: ['Корица', 'Апельсиновый цвет', 'Тмин'], base: ['Ваниль', 'Бобы тонка', 'Сандал'] },
    longevityHours: 8, sillage: 4, accords: ['фужерный', 'ваниль', 'пряный'],
    desc: 'Легенда 1995 года от Франсиса Куркджяна: лаванда и ваниль в тельняшке, с которой всё началось.',
    accent: '#3E6EA8',
  },
  {
    slug: 'jpg-le-male-le-parfum', brand: 'Jean Paul Gaultier', name: 'Le Male Le Parfum',
    price: 13900, volume: 125, concentration: 'Parfum', gender: 'м', tags: [],
    notes: { top: ['Кардамон', 'Бергамот'], heart: ['Лаванда', 'Ирис'], base: ['Ваниль', 'Сандал', 'Амбра'] },
    longevityHours: 10, sillage: 4, accords: ['ваниль', 'восточный', 'пудровый'],
    desc: 'Ирисовая ваниль в матросской форме: глубже, взрослее и стойче классического Le Male.',
    accent: '#1E3A6E',
  },
  {
    slug: 'jpg-scandal-pour-homme', brand: 'Jean Paul Gaultier', name: 'Scandal Pour Homme',
    price: 12500, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Мандарин', 'Шалфей мускатный'], heart: ['Карамель', 'Бобы тонка'], base: ['Ветивер', 'Древесные ноты'] },
    longevityHours: 7, sillage: 3, accords: ['гурманский', 'сладкий', 'древесный'],
    desc: 'Солёная карамель на ветивере — сладкий скандал в боксёрских перчатках.',
    accent: '#D0A030',
  },
  {
    slug: 'armani-code-parfum', brand: 'Giorgio Armani', name: 'Armani Code Parfum',
    price: 15500, volume: 75, concentration: 'Parfum', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Лист бергамота'], heart: ['Ирис', 'Шалфей', 'Альдегиды'], base: ['Бобы тонка', 'Кедр'] },
    longevityHours: 9, sillage: 3, accords: ['пудровый', 'древесный', 'амбра'],
    desc: 'Ночной код Armani: пудровый ирис и тонка — смокинг, застёгнутый на все пуговицы.',
    accent: '#1A1A1E',
  },
  {
    slug: 'armani-stronger-with-you', brand: 'Giorgio Armani', name: 'Emporio Armani Stronger With You',
    price: 11900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Каштан', 'Сахар', 'Розовый перец'], heart: ['Шалфей', 'Лаванда'], base: ['Ваниль', 'Дымные ноты'] },
    longevityHours: 8, sillage: 4, accords: ['сладкий', 'гурманский', 'дымный'],
    desc: 'Засахаренный каштан — оригинал, с которого началась самая комплиментарная линейка Armani.',
    accent: '#7A4A2E',
  },
  {
    slug: 'boss-the-scent', brand: 'Hugo Boss', name: 'Boss The Scent',
    price: 10900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Имбирь', 'Бергамот'], heart: ['Плод манинки', 'Лаванда'], base: ['Кожа', 'Древесные ноты'] },
    longevityHours: 7, sillage: 3, accords: ['пряный', 'кожаный', 'фруктовый'],
    desc: 'Имбирь и экзотическая манинка на замшевой коже — деловое обольщение от Boss.',
    accent: '#6E5A3E',
  },
  {
    slug: 'boss-bottled-parfum', brand: 'Hugo Boss', name: 'Boss Bottled Parfum',
    price: 14500, volume: 100, concentration: 'Parfum', gender: 'м', tags: [],
    notes: { top: ['Ладан', 'Мандарин'], heart: ['Инжир', 'Ирис'], base: ['Кедр', 'Кожа'] },
    longevityHours: 10, sillage: 3, accords: ['кожаный', 'древесный', 'пряный'],
    desc: 'Взрослая версия легендарного Bottled: ладан, инжир и кожа — костюм, сшитый по фигуре.',
    accent: '#3A3230',
  },
  {
    slug: 'lacoste-l1212-blanc', brand: 'Lacoste', name: 'L.12.12 Blanc',
    price: 8900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Грейпфрут', 'Розмарин', 'Кардамон'], heart: ['Иланг-иланг', 'Тубероза'], base: ['Кедр', 'Замша', 'Ветивер'] },
    longevityHours: 6, sillage: 2, accords: ['свежий', 'цветочный', 'древесный'],
    desc: 'Белое поло во флаконе: чистый, спортивный и безотказный аромат на каждый день.',
    accent: '#E8E8E0',
  },
  {
    slug: 'ck-one', brand: 'Calvin Klein', name: 'CK One',
    price: 8500, volume: 100, concentration: 'Eau de Toilette', gender: 'у', tags: [],
    notes: { top: ['Лимон', 'Бергамот', 'Ананас'], heart: ['Жасмин', 'Фиалка', 'Мускатный орех'], base: ['Мускус', 'Зелёный чай', 'Амбра'] },
    longevityHours: 6, sillage: 2, accords: ['цитрусовый', 'свежий', 'зелёный'],
    desc: 'Первый культовый унисекс 90-х: цитрус и зелёный чай — свежесть, которая никогда не устареет.',
    accent: '#D8D8D8',
  },
  {
    slug: 'ck-eternity-for-men', brand: 'Calvin Klein', name: 'Eternity For Men',
    price: 8900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Лаванда', 'Лимон', 'Мандарин'], heart: ['Шалфей', 'Базилик', 'Жасмин'], base: ['Сандал', 'Ветивер', 'Мускус'] },
    longevityHours: 7, sillage: 2, accords: ['фужерный', 'свежий', 'древесный'],
    desc: 'Классика 1990 года о вечных ценностях: травы и сандал — аромат чистой уверенности.',
    accent: '#A8B8B0',
  },
  {
    slug: 'montblanc-explorer', brand: 'Montblanc', name: 'Explorer',
    price: 9500, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Розовый перец'], heart: ['Ветивер', 'Кожа'], base: ['Пачули', 'Амброксан'] },
    longevityHours: 8, sillage: 3, accords: ['древесный', 'кожаный', 'свежий'],
    desc: 'Народный ответ дорогой нише: бергамот, ветивер и пачули по-настоящему честного качества.',
    accent: '#2E3E50',
  },
  {
    slug: 'montblanc-legend', brand: 'Montblanc', name: 'Legend',
    price: 8900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Лаванда', 'Ананас', 'Бергамот'], heart: ['Яблоко', 'Герань', 'Дубовый мох'], base: ['Бобы тонка', 'Сандал'] },
    longevityHours: 7, sillage: 3, accords: ['фужерный', 'фруктовый', 'свежий'],
    desc: 'Фужерная классика на каждый день — надёжный, как перьевая ручка Montblanc.',
    accent: '#1E2430',
  },
  {
    slug: 'azzaro-the-most-wanted', brand: 'Azzaro', name: 'The Most Wanted',
    price: 12900, volume: 100, concentration: 'EDP Intense', gender: 'м', tags: ['хит'],
    notes: { top: ['Кардамон', 'Имбирь'], heart: ['Карамель', 'Пряности'], base: ['Амбровое дерево', 'Ваниль'] },
    longevityHours: 10, sillage: 4, accords: ['сладкий', 'гурманский', 'амбра'],
    desc: 'Карамель на амбровом дереве — «самый разыскиваемый» вечерний аромат клубного сезона.',
    accent: '#A08828',
  },
  {
    slug: 'azzaro-chrome', brand: 'Azzaro', name: 'Chrome',
    price: 8500, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Лимон', 'Бергамот', 'Розмарин'], heart: ['Жасмин', 'Цикламен', 'Дубовый мох'], base: ['Мускус', 'Кедр'] },
    longevityHours: 6, sillage: 2, accords: ['цитрусовый', 'свежий', 'акватический'],
    desc: 'Металлическая свежесть 90-х: лимон и прохлада — проверенный летний ветеран.',
    accent: '#9EC8E0',
  },
  {
    slug: 'vr-spicebomb-extreme', brand: 'Viktor & Rolf', name: 'Spicebomb Extreme',
    price: 15900, volume: 90, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Чёрный перец', 'Лаванда', 'Грейпфрут'], heart: ['Корица', 'Шафран', 'Тмин'], base: ['Табак', 'Ваниль', 'Бурбон'] },
    longevityHours: 11, sillage: 5, accords: ['пряный', 'табачный', 'ваниль'],
    desc: 'Граната с корицей и табаком: зимний шлейф-взрыв, один из самых мощных дизайнерских ароматов.',
    accent: '#8E3A20',
  },
  {
    slug: 'valentino-uomo-born-in-roma', brand: 'Valentino', name: 'Uomo Born in Roma',
    price: 13900, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Минеральные соли', 'Листья фиалки'], heart: ['Шалфей', 'Имбирь'], base: ['Копчёный ветивер', 'Древесные ноты'] },
    longevityHours: 8, sillage: 3, accords: ['пряный', 'древесный', 'свежий'],
    desc: 'Римский рок-шик: соль, имбирь и дымный ветивер под шипами Rockstud.',
    accent: '#2A2A2E',
  },
  {
    slug: 'burberry-hero-edp', brand: 'Burberry', name: 'Hero Eau de Parfum',
    price: 12900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Сосновые иглы', 'Бергамот'], heart: ['Ладан', 'Бензоин'], base: ['Атласский кедр', 'Виргинский кедр'] },
    longevityHours: 8, sillage: 3, accords: ['древесный', 'дымный', 'свежий'],
    desc: 'Сосна, ладан и три вида кедра — лесной герой из кампании с Адамом Драйвером.',
    accent: '#4A5A48',
  },
];
