import type { RawProduct } from '../products';

/* ─── СЕГМЕНТ: АРАБСКИЕ ДОМА ───
 * Arabian Oud · Lattafa · Afnan · Armaf · Rasasi · Al Haramain · Swiss Arabian · Ajmal
 */
export const SEG_ARAB: RawProduct[] = [
  /* ─── ARABIAN OUD ─── */
  {
    slug: 'arabian-oud-kalemat-black', brand: 'Arabian Oud', name: 'Kalemat Black',
    price: 12900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Базилик', 'Ладан', 'Фрукты'], heart: ['Ваниль', 'Древесные ноты'], base: ['Амбра', 'Камбоджийский уд'] },
    longevityHours: 12, sillage: 4, accords: ['сладкий', 'дымный', 'уд'],
    desc: 'Культовый «чёрный Калемат»: дымная ваниль и камбоджийский уд — лучший первый уд по мнению всего мира.',
    accent: '#3A2E26',
  },
  {
    slug: 'arabian-oud-woody-intense', brand: 'Arabian Oud', name: 'Woody Intense',
    price: 15900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Гелиотроп', 'Розмарин'], heart: ['Герань', 'Кардамон'], base: ['Мускус', 'Пачули', 'Ваниль'] },
    longevityHours: 14, sillage: 5, accords: ['древесный', 'уд', 'пряный'],
    desc: 'Ядерная версия легендарного Woody: плотный уд и специи, которые держатся на одежде сутками.',
    accent: '#5C3B1E',
  },
  {
    slug: 'arabian-oud-madawi-gold', brand: 'Arabian Oud', name: 'Madawi Gold Edition',
    price: 19900, volume: 90, concentration: 'Eau de Parfum', gender: 'ж', tags: ['новинка'],
    notes: { top: ['Красные фрукты', 'Кардамон'], heart: ['Бобы тонка', 'Цветы ананаса', 'Жасмин'], base: ['Ваниль', 'Пачули'] },
    longevityHours: 12, sillage: 5, accords: ['фруктовый', 'сладкий', 'гурманский'],
    desc: 'Юбилейное творение Доминика Ропьона: карамелизованный ананас и ваниль в золотом флаконе к 40-летию дома.',
    accent: '#D4A017',
  },
  {
    slug: 'arabian-oud-resala', brand: 'Arabian Oud', name: 'Resala',
    price: 13900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Шоколад', 'Шафран'], heart: ['Лепестки розы', 'Древесные ноты'], base: ['Ваниль', 'Амбра'] },
    longevityHours: 12, sillage: 4, accords: ['гурманский', 'сладкий', 'восточный'],
    desc: 'Тёмный шоколад с розой и шафраном: десертный восток, который звучит дороже многих ниш.',
    accent: '#6B3F2A',
  },
  {
    slug: 'arabian-oud-sultani', brand: 'Arabian Oud', name: 'Sultani',
    price: 18900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Ягоды', 'Кардамон'], heart: ['Роза', 'Карамель'], base: ['Мускус', 'Древесные ноты', 'Амбра'] },
    longevityHours: 10, sillage: 3, accords: ['сладкий', 'мускусный', 'древесный'],
    desc: 'Парфюм саудовской элиты: ягоды и мускусные древесные ноты с высочайшим содержанием масел.',
    accent: '#8C2F39',
  },
  {
    slug: 'arabian-oud-ghroob', brand: 'Arabian Oud', name: 'Ghroob',
    price: 11900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Шафран', 'Флёрдоранж', 'Корица'], heart: ['Гардения', 'Болгарская роза', 'Жасмин'], base: ['Сандал', 'Белая амбра', 'Мускус'] },
    longevityHours: 10, sillage: 4, accords: ['цветочный', 'восточный', 'уд'],
    desc: 'Один из лучших шафранов в парфюмерии: солнечный флёрдоранж на кремовом сандале и мягком уде.',
    accent: '#C96F2D',
  },
  {
    slug: 'arabian-oud-majestic-special-oud', brand: 'Arabian Oud', name: 'Majestic Special Oud',
    price: 16900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Шафран', 'Розмарин'], heart: ['Таифская роза', 'Флёрдоранж'], base: ['Уд', 'Сандал', 'Ваниль'] },
    longevityHours: 14, sillage: 5, accords: ['уд', 'восточный', 'древесный'],
    desc: 'Настоящая таифская роза и уд без компромиссов — величественная классика для особых выходов.',
    accent: '#7A1F2B',
  },
  {
    slug: 'arabian-oud-royal-oud', brand: 'Arabian Oud', name: 'Royal Oud',
    price: 14900, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Шафран', 'Бергамот'], heart: ['Роза', 'Уд'], base: ['Амбра', 'Сандал', 'Мускус'] },
    longevityHours: 12, sillage: 4, accords: ['уд', 'пряный', 'амбра'],
    desc: 'Королевский уд в классическом прочтении Эр-Рияда: строго, глубоко и очень статусно.',
    accent: '#4B3621',
  },
  {
    slug: 'arabian-oud-saffron-oud', brand: 'Arabian Oud', name: 'Saffron Oud',
    price: 12900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: ['новинка'],
    notes: { top: ['Шафран', 'Пряности'], heart: ['Роза', 'Уд'], base: ['Амбра', 'Древесные ноты'] },
    longevityHours: 11, sillage: 4, accords: ['пряный', 'уд', 'амбра'],
    desc: 'Свежий релиз дома: дуэт драгоценного шафрана и уда — восток в самом чистом виде.',
    accent: '#B8500F',
  },
  {
    slug: 'arabian-oud-rosewood', brand: 'Arabian Oud', name: 'Rosewood',
    price: 10900, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Дамасская роза', 'Малина'], heart: ['Палисандр', 'Герань'], base: ['Мускус', 'Амбра'] },
    longevityHours: 9, sillage: 3, accords: ['цветочный', 'древесный', 'мускусный'],
    desc: 'Бархатная роза на розовом дереве: самый носибельный и «европейский» аромат саудовского дома.',
    accent: '#B04A5A',
  },

  /* ─── LATTAFA ─── */
  {
    slug: 'lattafa-oud-mood', brand: 'Lattafa', name: 'Oud Mood',
    price: 2990, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Роза', 'Шафран', 'Пимента'], heart: ['Уд', 'Карамель', 'Пачули'], base: ['Амбра', 'Ладан', 'Мускус'] },
    longevityHours: 10, sillage: 4, accords: ['восточный', 'уд', 'сладкий'],
    desc: 'Дымная карамель, ладан и уд: восточная классика Lattafa, которая звучит в разы дороже цены.',
    accent: '#8A5A2B',
  },
  {
    slug: 'lattafa-qaed-al-fursan', brand: 'Lattafa', name: 'Qaed Al Fursan',
    price: 2790, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Ананас', 'Шафран'], heart: ['Пихтовый бальзам', 'Жасмин'], base: ['Кедр', 'Амбра', 'Уд'] },
    longevityHours: 8, sillage: 3, accords: ['фруктовый', 'древесный', 'уд'],
    desc: '«Предводитель всадников»: сочный ананас на дымном кедре — восточный ответ Aventus за копейки.',
    accent: '#C9A227',
  },
  {
    slug: 'lattafa-ameer-al-oudh-intense-oud', brand: 'Lattafa', name: 'Ameer Al Oudh Intense Oud',
    price: 3190, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Уд', 'Пряности'], heart: ['Ваниль', 'Сахар'], base: ['Древесные ноты', 'Ладан'] },
    longevityHours: 12, sillage: 5, accords: ['уд', 'сладкий', 'дымный'],
    desc: 'Сладкий дымный уд-«зверь»: проекция на весь вечер и шлейф, о котором будут спрашивать.',
    accent: '#3E2723',
  },
  {
    slug: 'lattafa-maahir-legacy', brand: 'Lattafa', name: 'Maahir Legacy',
    price: 3490, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Лайм', 'Мята', 'Грейпфрут'], heart: ['Чёрный перец', 'Розмарин', 'Ладан'], base: ['Амброксан', 'Ветивер', 'Дубовый мох'] },
    longevityHours: 9, sillage: 4, accords: ['свежий', 'фужерный', 'древесный'],
    desc: 'Мятно-цитрусовый заряд с амброксаном: свежий офисный «комплиментщик» на каждый день.',
    accent: '#2E7D6B',
  },
  {
    slug: 'lattafa-eclaire', brand: 'Lattafa', name: 'Eclaire',
    price: 3990, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: ['хит'],
    notes: { top: ['Карамель', 'Молоко', 'Сахар'], heart: ['Мёд', 'Белые цветы'], base: ['Ваниль', 'Пралине', 'Мускус'] },
    longevityHours: 8, sillage: 3, accords: ['гурманский', 'сладкий', 'ваниль'],
    desc: 'Вирусный молочно-карамельный эклер из TikTok: уютный гурман, разлетающийся с полок за часы.',
    accent: '#E8C39E',
  },
  {
    slug: 'lattafa-mayar', brand: 'Lattafa', name: 'Mayar',
    price: 3290, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Личи', 'Малина', 'Лист фиалки'], heart: ['Белая роза', 'Пион', 'Жасмин'], base: ['Мускус', 'Ваниль'] },
    longevityHours: 7, sillage: 3, accords: ['цветочный', 'фруктовый', 'мускусный'],
    desc: 'Личи, пион и белая роза: лёгкий «дорогой» флораль в духе Delina — за десятую часть цены.',
    accent: '#E89BB4',
  },
  {
    slug: 'lattafa-haya', brand: 'Lattafa', name: 'Haya',
    price: 3190, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Шампанское', 'Клубника', 'Мандарин'], heart: ['Гардения', 'Жасмин', 'Ванильная орхидея'], base: ['Амбра', 'Сандал', 'Каштан'] },
    longevityHours: 7, sillage: 3, accords: ['фруктовый', 'сладкий', 'цветочный'],
    desc: 'Игристое шампанское с клубникой и гарденией — праздничный аромат хорошего настроения.',
    accent: '#F2C94C',
  },
  {
    slug: 'lattafa-ramz-gold', brand: 'Lattafa', name: 'Ramz Lattafa Gold',
    price: 2890, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Яблоко', 'Персик', 'Груша'], heart: ['Роза', 'Жасмин самбак', 'Флёрдоранж'], base: ['Сандал', 'Белый мускус', 'Ваниль'] },
    longevityHours: 9, sillage: 3, accords: ['фруктовый', 'цветочный', 'сладкий'],
    desc: 'Сочные фрукты на сандаловой базе: универсальный «золотой» Lattafa на 8–12 часов носки.',
    accent: '#C9922E',
  },
  {
    slug: 'lattafa-yara-tous', brand: 'Lattafa', name: 'Yara Tous',
    price: 3490, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: ['хит'],
    notes: { top: ['Манго', 'Кокос', 'Маракуйя'], heart: ['Жасмин', 'Флёрдоранж', 'Гелиотроп'], base: ['Ваниль', 'Мускус', 'Кашмеран'] },
    longevityHours: 7, sillage: 3, accords: ['фруктовый', 'сладкий', 'цветочный'],
    desc: 'Сливочное манго с кокосом — тропический бестселлер линейки Yara, любимец соцсетей этого лета.',
    accent: '#F4A259',
  },
  {
    slug: 'lattafa-al-qiam-gold', brand: 'Lattafa', name: 'Al Qiam Gold',
    price: 4990, volume: 100, concentration: 'Extrait de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Яблоко', 'Бергамот', 'Лаванда'], heart: ['Герань', 'Пачули'], base: ['Ваниль', 'Гваяковое дерево', 'Мускус'] },
    longevityHours: 10, sillage: 4, accords: ['пряный', 'сладкий', 'древесный'],
    desc: 'Главный «убийца» Layton: пряное яблоко с ванилью в экстрактной концентрации — хит перепродаж.',
    accent: '#D4AF37',
  },

  /* ─── AFNAN ─── */
  {
    slug: 'afnan-supremacy-silver', brand: 'Afnan', name: 'Supremacy Silver',
    price: 5490, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Ананас', 'Чёрная смородина', 'Бергамот'], heart: ['Берёза', 'Пачули', 'Роза'], base: ['Мускус', 'Дубовый мох', 'Амбергрис'] },
    longevityHours: 8, sillage: 4, accords: ['фруктовый', 'дымный', 'шипровый'],
    desc: 'Номинант премии Fragrantica как замена Aventus: дымный ананас и берёза по-эмиратски честно.',
    accent: '#AEB6BF',
  },
  {
    slug: 'afnan-supremacy-not-only-intense', brand: 'Afnan', name: 'Supremacy Not Only Intense',
    price: 5990, volume: 100, concentration: 'Extrait de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Ананас', 'Чёрная смородина'], heart: ['Берёза', 'Жасмин'], base: ['Амбергрис', 'Дубовый мох', 'Ваниль'] },
    longevityHours: 12, sillage: 5, accords: ['фруктовый', 'дымный', 'амбра'],
    desc: 'Между Hacivat и Aventus: экстракт-«ядерка», которая живёт на рубашке больше суток.',
    accent: '#1B1B1F',
  },
  {
    slug: 'afnan-9am', brand: 'Afnan', name: '9AM',
    price: 4490, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Лимон', 'Мандарин', 'Розовый перец'], heart: ['Лаванда', 'Флёрдоранж', 'Зелёное яблоко'], base: ['Мускус', 'Мох', 'Кедр'] },
    longevityHours: 7, sillage: 3, accords: ['цитрусовый', 'свежий', 'мускусный'],
    desc: 'Запах свежевыстиранного белья в лимонном саду: идеальное «чистое» утро с 9AM.',
    accent: '#F5E960',
  },
  {
    slug: 'afnan-turathi-blue', brand: 'Afnan', name: 'Turathi Blue',
    price: 4990, volume: 90, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Лимон', 'Грейпфрут'], heart: ['Имбирь', 'Древесные ноты'], base: ['Мускус', 'Амброксан'] },
    longevityHours: 8, sillage: 4, accords: ['цитрусовый', 'свежий', 'древесный'],
    desc: 'Близнец Bvlgari Tygar: ледяной грейпфрут на амброксане — летняя свежесть с характером.',
    accent: '#2D6CDF',
  },
  {
    slug: 'afnan-9pm-rebel', brand: 'Afnan', name: '9PM Rebel',
    price: 5490, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: ['новинка'],
    notes: { top: ['Зелёное яблоко', 'Ананас', 'Мандарин'], heart: ['Кедр', 'Ваниль', 'Дубовый мох'], base: ['Амбергрис', 'Карамель', 'Мускус'] },
    longevityHours: 9, sillage: 4, accords: ['фруктовый', 'сладкий', 'древесный'],
    desc: 'Дерзкий флэнкер легендарного 9PM: хрустящее яблоко и солёная карамель для вечернего выхода.',
    accent: '#5E60CE',
  },

  /* ─── ARMAF ─── */
  {
    slug: 'armaf-club-de-nuit-sillage', brand: 'Armaf', name: 'Club de Nuit Sillage',
    price: 4290, volume: 105, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Бергамот', 'Лимон', 'Чёрная смородина'], heart: ['Роза', 'Жасмин', 'Ирис'], base: ['Амброксан', 'Мускус', 'Сандал'] },
    longevityHours: 8, sillage: 3, accords: ['свежий', 'мускусный', 'цитрусовый'],
    desc: 'Хрустально-чистая свежесть в духе Silver Mountain Water — металлический холодок дорогой воды.',
    accent: '#BFD7EA',
  },
  {
    slug: 'armaf-club-de-nuit-milestone', brand: 'Armaf', name: 'Club de Nuit Milestone',
    price: 4290, volume: 105, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Морские ноты', 'Красные фрукты', 'Бергамот'], heart: ['Фиалка', 'Сандал'], base: ['Мускус', 'Амброксан', 'Ветивер'] },
    longevityHours: 7, sillage: 3, accords: ['акватический', 'фруктовый', 'свежий'],
    desc: 'Солёный арбуз и морской бриз: летний Armaf в духе Millésime Impérial с отличной стойкостью.',
    accent: '#48A9A6',
  },
  {
    slug: 'armaf-club-de-nuit-woman', brand: 'Armaf', name: 'Club de Nuit Woman',
    price: 3790, volume: 105, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Лимон', 'Чёрная смородина', 'Апельсин'], heart: ['Роза', 'Жасмин', 'Флёрдоранж'], base: ['Ваниль', 'Мускус', 'Амбра'] },
    longevityHours: 8, sillage: 3, accords: ['фруктовый', 'цветочный', 'сладкий'],
    desc: 'Женская легенда линейки Club de Nuit: искристые фрукты и ваниль — вечерняя классика без переплат.',
    accent: '#C2185B',
  },
  {
    slug: 'armaf-odyssey-mandarin-sky', brand: 'Armaf', name: 'Odyssey Mandarin Sky',
    price: 3990, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Мандарин', 'Апельсин', 'Шафран'], heart: ['Карамель', 'Бобы тонка'], base: ['Амброксан', 'Кедр', 'Ветивер'] },
    longevityHours: 9, sillage: 4, accords: ['цитрусовый', 'гурманский', 'сладкий'],
    desc: 'Вирусный мандарин в карамели: главный бюджетный комплиментщик последних сезонов.',
    accent: '#F28C28',
  },
  {
    slug: 'armaf-tres-nuit', brand: 'Armaf', name: 'Tres Nuit',
    price: 2990, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Ирис', 'Лимон', 'Вербена'], heart: ['Лаванда', 'Фиалка'], base: ['Амбергрис', 'Сандал'] },
    longevityHours: 6, sillage: 2, accords: ['свежий', 'фужерный', 'зелёный'],
    desc: 'Зелёная классика в духе Green Irish Tweed: свежескошенная трава и вербена на каждый день.',
    accent: '#4C9A2A',
  },
  {
    slug: 'armaf-hunter-intense', brand: 'Armaf', name: 'Hunter Intense',
    price: 3290, volume: 100, concentration: 'Eau de Toilette', gender: 'м', tags: [],
    notes: { top: ['Грейпфрут', 'Морские ноты'], heart: ['Лавровый лист', 'Жасмин'], base: ['Амбра', 'Гваяковое дерево', 'Мускус'] },
    longevityHours: 6, sillage: 3, accords: ['свежий', 'сладкий', 'акватический'],
    desc: 'Свежесладкий спортивный драйв в духе Invictus — бросил в спортивную сумку и пахнешь победой.',
    accent: '#3D5A80',
  },

  /* ─── RASASI ─── */
  {
    slug: 'rasasi-hawas-ice', brand: 'Rasasi', name: 'Hawas Ice',
    price: 5990, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Яблоко', 'Итальянский лимон', 'Бадьян'], heart: ['Слива', 'Флёрдоранж', 'Кардамон'], base: ['Мускус', 'Амбра', 'Мох'] },
    longevityHours: 9, sillage: 4, accords: ['свежий', 'акватический', 'фруктовый'],
    desc: 'Ледяной флэнкер легендарного Hawas: морозное яблоко и цитрус, вирусный хит жарких месяцев.',
    accent: '#7FDBFF',
  },
  {
    slug: 'rasasi-la-yuqawam', brand: 'Rasasi', name: 'La Yuqawam Homme',
    price: 6990, volume: 75, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Малина', 'Шафран', 'Тимьян'], heart: ['Ладан', 'Жасмин'], base: ['Кожа', 'Замша', 'Амбра'] },
    longevityHours: 10, sillage: 4, accords: ['кожаный', 'дымный', 'фруктовый'],
    desc: '«Неотразимый» ответ Tuscan Leather: малина на дорогой замше — брутальная роскошь Rasasi.',
    accent: '#5D2A1A',
  },
  {
    slug: 'rasasi-fattan', brand: 'Rasasi', name: 'Fattan',
    price: 4990, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Грейпфрут', 'Бергамот', 'Розовый перец'], heart: ['Ветивер', 'Кедр', 'Пачули'], base: ['Дубовый мох', 'Бензоин', 'Амбра'] },
    longevityHours: 8, sillage: 3, accords: ['цитрусовый', 'древесный', 'шипровый'],
    desc: 'Сухой ветивер и сочный грейпфрут в духе Terre d’Hermès — интеллигентная классика на работу.',
    accent: '#B85C38',
  },
  {
    slug: 'rasasi-shuhrah', brand: 'Rasasi', name: 'Shuhrah Pour Homme',
    price: 4490, volume: 90, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Томатный лист', 'Роза', 'Фрезия'], heart: ['Сандал', 'Кедр', 'Жасмин'], base: ['Кожа', 'Уд', 'Мускус'] },
    longevityHours: 10, sillage: 4, accords: ['зелёный', 'древесный', 'кожаный'],
    desc: 'Недооценённая бомба: зелёный томатный лист на коже и уде — уникально и оглушительно стойко.',
    accent: '#356859',
  },
  {
    slug: 'rasasi-daarej', brand: 'Rasasi', name: 'Daarej Pour Homme',
    price: 3990, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Кумин', 'Кардамон', 'Полынь'], heart: ['Роза', 'Корень ириса'], base: ['Ваниль', 'Бобы тонка', 'Амбра'] },
    longevityHours: 8, sillage: 4, accords: ['пряный', 'восточный', 'ваниль'],
    desc: 'Пряная роза на тёплой ванили: настоящий восточный характер, который носят и мужчины, и женщины.',
    accent: '#9C6615',
  },

  /* ─── AL HARAMAIN ─── */
  {
    slug: 'al-haramain-l-aventure', brand: 'Al Haramain', name: 'L’Aventure',
    price: 6490, volume: 100, concentration: 'Eau de Parfum', gender: 'м', tags: ['хит'],
    notes: { top: ['Лимон', 'Бергамот', 'Элеми'], heart: ['Древесные ноты', 'Жасмин', 'Ландыш'], base: ['Мускус', 'Пачули', 'Амбра'] },
    longevityHours: 8, sillage: 4, accords: ['фруктовый', 'дымный', 'древесный'],
    desc: 'Самая известная альтернатива Aventus: 95% сходства в чёрном гранёном флаконе за 5% цены.',
    accent: '#111827',
  },
  {
    slug: 'al-haramain-l-aventure-blanche', brand: 'Al Haramain', name: 'L’Aventure Blanche',
    price: 6490, volume: 100, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Бергамот', 'Лимон', 'Зелёные ноты'], heart: ['Жасмин', 'Роза', 'Ландыш'], base: ['Белый мускус', 'Сандал', 'Амбра'] },
    longevityHours: 7, sillage: 3, accords: ['свежий', 'цветочный', 'мускусный'],
    desc: 'Белоснежная версия бестселлера: чистые цветы и белый мускус — свежесть дорогого отеля.',
    accent: '#EAEAEA',
  },
  {
    slug: 'al-haramain-amber-oud-bleu', brand: 'Al Haramain', name: 'Amber Oud Bleu Edition',
    price: 7490, volume: 60, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Грейпфрут', 'Лимон', 'Мята'], heart: ['Имбирь', 'Ветивер', 'Жасмин'], base: ['Ладан', 'Сандал', 'Кедр'] },
    longevityHours: 8, sillage: 4, accords: ['свежий', 'цитрусовый', 'древесный'],
    desc: 'Голубой Amber Oud: искристый цитрус и ладан в духе Bleu de Chanel — свежесть на все сезоны.',
    accent: '#1E5AA8',
  },
  {
    slug: 'al-haramain-detour-noir', brand: 'Al Haramain', name: 'Détour Noir',
    price: 5990, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Яблоко', 'Лаванда', 'Фиалка'], heart: ['Ваниль', 'Пачули', 'Бергамот'], base: ['Сандал', 'Кардамон', 'Гваяковое дерево'] },
    longevityHours: 10, sillage: 4, accords: ['сладкий', 'пряный', 'древесный'],
    desc: 'Знаменитый «Layton за копейки»: пряное яблоко с ванилью, собравшее армию поклонников.',
    accent: '#2C2C34',
  },

  /* ─── SWISS ARABIAN ─── */
  {
    slug: 'swiss-arabian-shaghaf-oud', brand: 'Swiss Arabian', name: 'Shaghaf Oud',
    price: 5490, volume: 75, concentration: 'Eau de Parfum', gender: 'у', tags: ['хит'],
    notes: { top: ['Шафран', 'Пряности'], heart: ['Уд', 'Роза'], base: ['Пралине', 'Ваниль', 'Амбра'] },
    longevityHours: 10, sillage: 4, accords: ['уд', 'сладкий', 'восточный'],
    desc: 'Пралине и шафран на бархатном уде — визитная карточка Swiss Arabian и любимец обзорщиков.',
    accent: '#8E5B3A',
  },
  {
    slug: 'swiss-arabian-shaghaf-oud-aswad', brand: 'Swiss Arabian', name: 'Shaghaf Oud Aswad',
    price: 5990, volume: 75, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Роза', 'Шафран', 'Тимьян'], heart: ['Уд', 'Пачули', 'Жасмин'], base: ['Кожа', 'Амбра', 'Сандал'] },
    longevityHours: 11, sillage: 4, accords: ['уд', 'кожаный', 'дымный'],
    desc: 'Чёрная версия Shaghaf: джемовая роза, бахур и кожа — тёмный, гипнотический вечерний уд.',
    accent: '#241F26',
  },
  {
    slug: 'swiss-arabian-layali-rouge', brand: 'Swiss Arabian', name: 'Layali Rouge',
    price: 2190, volume: 15, concentration: 'Масляные духи', gender: 'ж', tags: [],
    notes: { top: ['Гибискус', 'Кокос'], heart: ['Роза', 'Персик'], base: ['Манго', 'Ананас', 'Папайя'] },
    longevityHours: 6, sillage: 2, accords: ['фруктовый', 'сладкий', 'пудровый'],
    desc: 'Культовое масло «красные ночи»: тропические фрукты и пудровая роза прямо на коже, без спирта.',
    accent: '#D7263D',
  },
  {
    slug: 'swiss-arabian-casablanca', brand: 'Swiss Arabian', name: 'Casablanca',
    price: 4990, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Яблоко', 'Виноград'], heart: ['Ирис', 'Белые древесные ноты', 'Пачули'], base: ['Карамель', 'Амбра', 'Замша'] },
    longevityHours: 9, sillage: 4, accords: ['сладкий', 'гурманский', 'фруктовый'],
    desc: 'Яблоко в карамели с виноградом: самый популярный аромат Swiss Arabian — десертный магнит.',
    accent: '#A0522D',
  },

  /* ─── AJMAL ─── */
  {
    slug: 'ajmal-amber-wood', brand: 'Ajmal', name: 'Amber Wood',
    price: 6990, volume: 100, concentration: 'Eau de Parfum', gender: 'у', tags: [],
    notes: { top: ['Кардамон', 'Яблоко', 'Лаванда'], heart: ['Кедр', 'Ирис'], base: ['Амбра', 'Пачули', 'Древесные ноты'] },
    longevityHours: 9, sillage: 3, accords: ['амбра', 'древесный', 'пудровый'],
    desc: 'Тёплая амбра на пудровом ирисе и кедре: тихая роскошь индийского дома с 70-летней историей.',
    accent: '#B4713D',
  },
  {
    slug: 'ajmal-aristocrat', brand: 'Ajmal', name: 'Aristocrat',
    price: 4490, volume: 75, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Бергамот', 'Лайм', 'Арбуз'], heart: ['Мускус', 'Лилия', 'Жасмин'], base: ['Уд', 'Кедр', 'Амбра'] },
    longevityHours: 7, sillage: 3, accords: ['свежий', 'фруктовый', 'древесный'],
    desc: 'Свежий арбузный джентльмен с лёгким удом в базе — аристократичный офисный вариант.',
    accent: '#3E7CB1',
  },
  {
    slug: 'ajmal-wisal', brand: 'Ajmal', name: 'Wisal',
    price: 4990, volume: 50, concentration: 'Eau de Parfum', gender: 'ж', tags: [],
    notes: { top: ['Пряности', 'Роза'], heart: ['Цветочные ноты', 'Сандал'], base: ['Мускус', 'Амбра'] },
    longevityHours: 8, sillage: 3, accords: ['цветочный', 'восточный', 'мускусный'],
    desc: 'Нежная восточная роза на сандале и мускусе: классика Ajmal, которую носят десятилетиями.',
    accent: '#C0688A',
  },
  {
    slug: 'ajmal-evoke', brand: 'Ajmal', name: 'Evoke for Him',
    price: 3990, volume: 90, concentration: 'Eau de Parfum', gender: 'м', tags: [],
    notes: { top: ['Лаванда', 'Зелёное яблоко', 'Бергамот'], heart: ['Кардамон', 'Гелиотроп', 'Ирис'], base: ['Сандал', 'Ветивер', 'Мускус'] },
    longevityHours: 8, sillage: 3, accords: ['фужерный', 'свежий', 'древесный'],
    desc: 'Ароматическая классика с сильной проекцией: лаванда и сандал на 8–10 часов уверенности.',
    accent: '#556B2F',
  },
];
